[pytest]
markers =
    smoke: mark a test as smoke scenario
    regression: mark a test as regression scenario
    positive: mark a test as positive scenario
    valid: mark a test as valid scenario
    usefixtures: mark a test as usefixtures scenario
    negative: mark a test as negative scenario
    performance: mark a test as performance scenario
    xfail: mark a test as xfail scenario
    security: mark a test as security scenario
