
# ********RoostGPT********
"""

# Test generated by RoostGPT for test API-test-py01 using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /auth/register_post for http method type POST 
# RoostTestHash=5d30eb1c66
# 
# 

roost_feedback [26/11/2025, 10:03:09 AM]:-\sFormat\sthe\stest
"""

# ********RoostGPT********

import json
import os
import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator


def load_test_data():
    """Load test data from auth_register.json file."""
    test_data_path = Path(__file__).parent / "auth_register.json"
    with open(test_data_path, "r") as f:
        return json.load(f)


ENDPOINT = "/auth/register"
HTTP_METHOD = "post"
API_SPEC_PATH = Path(__file__).parent / "api.json"


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize SwaggerSchemaValidator with API spec."""
    return SwaggerSchemaValidator(str(API_SPEC_PATH))


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load endpoint-specific test data from JSON file."""
    return load_test_data()


class TestAuthRegisterSuccess:
    """Test class for successful user registration scenarios."""

    @pytest.mark.smoke
    def test_register_user_with_required_fields_only(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": config_test_data.get("username", "testuser"),
            "email": config_test_data.get("email", "testuser@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code == 201, (
            f"Expected 201, got {response.status_code}. Response: {response.text}"
        )

        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "201", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

        response_data = response.json()
        assert "id" in response_data, "Response should contain 'id' field"
        assert "username" in response_data, "Response should contain 'username' field"
        assert "email" in response_data, "Response should contain 'email' field"

    @pytest.mark.smoke
    @pytest.mark.parametrize(
        "test_case",
        load_test_data(),
        ids=lambda tc: tc.get("scenario", "unknown"),
    )
    def test_register_user_from_test_data(
        self, api_client, config_test_data, schema_validator, test_case
    ):
        payload = {
            "username": test_case.get("username"),
            "email": test_case.get("email"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        if "firstName" in test_case:
            payload["firstName"] = test_case["firstName"]
        if "lastName" in test_case:
            payload["lastName"] = test_case["lastName"]

        response = api_client.post(ENDPOINT, json=payload)

        expected_status = test_case.get("statusCode", 201)
        assert response.status_code == expected_status, (
            f"Scenario: {test_case.get('scenario')} - "
            f"Expected {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )

        if expected_status == 201:
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, HTTP_METHOD, "201", response
            )
            assert validation_result["valid"], (
                f"Schema validation failed for scenario '{test_case.get('scenario')}': "
                f"{validation_result.get('message', 'Unknown error')}"
            )


class TestAuthRegisterValidation:
    """Test class for request validation and error scenarios."""

    def test_register_missing_username(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "email": config_test_data.get("email", "test@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code == 400, (
            f"Expected 400 for missing username, got {response.status_code}. "
            f"Response: {response.text}"
        )

        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "400", response
        )
        assert validation_result["valid"], (
            f"Error response schema validation failed: "
            f"{validation_result.get('message', 'Unknown error')}"
        )

    def test_register_missing_email(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": config_test_data.get("username", "testuser"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code == 400, (
            f"Expected 400 for missing email, got {response.status_code}. "
            f"Response: {response.text}"
        )

        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "400", response
        )
        assert validation_result["valid"], (
            f"Error response schema validation failed: "
            f"{validation_result.get('message', 'Unknown error')}"
        )

    def test_register_missing_password(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": config_test_data.get("username", "testuser"),
            "email": config_test_data.get("email", "test@example.com"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code == 400, (
            f"Expected 400 for missing password, got {response.status_code}. "
            f"Response: {response.text}"
        )

        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "400", response
        )
        assert validation_result["valid"], (
            f"Error response schema validation failed: "
            f"{validation_result.get('message', 'Unknown error')}"
        )

    def test_register_empty_request_body(self, api_client, schema_validator):
        response = api_client.post(ENDPOINT, json={})

        assert response.status_code == 400, (
            f"Expected 400 for empty body, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_register_invalid_email_format(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": config_test_data.get("username", "testuser"),
            "email": "invalid-email-format",
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code == 400, (
            f"Expected 400 for invalid email format, got {response.status_code}. "
            f"Response: {response.text}"
        )

    @pytest.mark.parametrize(
        "invalid_payload,description",
        [
            (
                {"username": "", "email": "test@example.com", "password": "P@ssw0rd!"},
                "empty username",
            ),
            (
                {"username": "user", "email": "", "password": "P@ssw0rd!"},
                "empty email",
            ),
            (
                {"username": "user", "email": "test@example.com", "password": ""},
                "empty password",
            ),
            (
                {"username": None, "email": "test@example.com", "password": "P@ssw0rd!"},
                "null username",
            ),
            (
                {"username": "user", "email": None, "password": "P@ssw0rd!"},
                "null email",
            ),
            (
                {"username": "user", "email": "test@example.com", "password": None},
                "null password",
            ),
        ],
        ids=[
            "empty_username",
            "empty_email",
            "empty_password",
            "null_username",
            "null_email",
            "null_password",
        ],
    )
    def test_register_invalid_field_values(
        self, api_client, schema_validator, invalid_payload, description
    ):
        response = api_client.post(ENDPOINT, json=invalid_payload)

        assert response.status_code == 400, (
            f"Expected 400 for {description}, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestAuthRegisterEdgeCases:
    """Test class for edge cases and boundary conditions."""

    def test_register_with_extra_fields(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": config_test_data.get("username", "testuser"),
            "email": config_test_data.get("email", "test@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
            "unexpectedField": "unexpected_value",
            "anotherExtra": 12345,
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code in [201, 400], (
            f"Expected 201 or 400, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_register_username_with_special_characters(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": "user@#$%^&*()",
            "email": config_test_data.get("email", "test@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code in [201, 400], (
            f"Expected 201 or 400, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_register_very_long_username(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": "a" * 1000,
            "email": config_test_data.get("email", "test@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code in [201, 400], (
            f"Expected 201 or 400 for long username, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_register_with_unicode_characters(
        self, api_client, config_test_data, schema_validator
    ):
        payload = {
            "username": "用户名测试",
            "email": config_test_data.get("email", "test@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(ENDPOINT, json=payload)

        assert response.status_code in [201, 400], (
            f"Expected 201 or 400 for unicode username, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_register_content_type_validation(self, api_client, config_test_data):
        payload = {
            "username": config_test_data.get("username", "testuser"),
            "email": config_test_data.get("email", "test@example.com"),
            "password": config_test_data.get("password", "P@ssw0rd!"),
        }

        response = api_client.post(
            ENDPOINT,
            data=json.dumps(payload),
            headers={"Content-Type": "text/plain"},
        )

        assert response.status_code in [400, 415], (
            f"Expected 400 or 415 for wrong content type, got {response.status_code}. "
            f"Response: {response.text}"
        )
