# ********RoostGPT********

# Test generated by RoostGPT for test API-test-yaml using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /api/v1/clusters/_get for http method type GET 
# RoostTestHash=30784b487f
# 
# 

# ********RoostGPT********
"""
API Test Suite for /api/v1/clusters/ endpoint

This module contains pytest tests for the ListClusters API endpoint.
Tests cover successful responses, schema validation, and edge cases.

Identified Endpoints:
- GET /api/v1/clusters/ - List available clusters

Security Schema:
- keystone: Token-based authentication via x-auth-token header

Response Status Codes:
- 200: OK - Returns array of cluster objects

Setup:
1. Ensure config.yml is properly configured with API host and auth token
2. Set environment variables API_HOST and x-auth-token if needed
3. Run tests with: pytest test_api_v1_clusters.py -v

To run smoke tests only: pytest test_api_v1_clusters.py -v -m smoke
"""

import json
import os
import pytest
from pathlib import Path

# Import validator
from validator import SwaggerSchemaValidator


# Constants
ENDPOINT = "/api/v1/clusters/"
HTTP_METHOD = "GET"
API_SPEC_PATH = "api.json"
TEST_DATA_FILE = "api_v1_clusters.json"


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load test data from JSON file for table-driven tests"""
    test_data_path = Path(__file__).parent / TEST_DATA_FILE
    if not test_data_path.exists():
        pytest.skip(f"Test data file not found: {TEST_DATA_FILE}")
    
    with open(test_data_path, 'r') as f:
        return json.load(f)


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize SwaggerSchemaValidator with API spec"""
    spec_path = Path(__file__).parent / API_SPEC_PATH
    if not spec_path.exists():
        pytest.skip(f"API spec file not found: {API_SPEC_PATH}")
    
    return SwaggerSchemaValidator(str(spec_path))


class TestListClustersSuccess:
    """Test class for successful ListClusters API responses"""
    
    @pytest.mark.smoke
    def test_list_clusters_success(self, api_client, schema_validator):
        """
        Test successful listing of clusters with valid authentication.
        
        This is a happy path test that validates:
        - API returns 200 status code
        - Response schema matches OpenAPI specification
        """
        response = api_client.get(ENDPOINT)
        
        assert response.status_code == 200, (
            f"Expected status code 200, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )
    
    def test_list_clusters_response_is_array(self, api_client):
        """Test that the response is an array as per specification"""
        response = api_client.get(ENDPOINT)
        
        assert response.status_code == 200
        
        response_data = response.json()
        assert isinstance(response_data, list), (
            f"Expected response to be an array, got {type(response_data).__name__}"
        )
    
    def test_list_clusters_array_items_structure(self, api_client):
        """Test that array items have expected structure with name property"""
        response = api_client.get(ENDPOINT)
        
        assert response.status_code == 200
        
        response_data = response.json()
        
        # If array is not empty, validate item structure
        for idx, item in enumerate(response_data):
            assert isinstance(item, dict), (
                f"Item at index {idx} should be an object, got {type(item).__name__}"
            )
            # name is optional per spec, but if present should be string
            if "name" in item:
                assert isinstance(item["name"], str), (
                    f"Item at index {idx}: 'name' should be string, "
                    f"got {type(item['name']).__name__}"
                )


class TestListClustersTableDriven:
    """Table-driven tests using data from JSON file"""
    
    def test_list_clusters_scenarios(self, api_client, endpoint_test_data, schema_validator):
        """
        Table-driven test that iterates through all test scenarios from JSON file.
        
        Each scenario in the JSON file contains:
        - body: Request body (not used for GET requests)
        - statusCode: Expected status code
        - scenario: Description of the test scenario
        """
        for test_case in endpoint_test_data:
            scenario = test_case.get("scenario", "Unknown scenario")
            expected_status = test_case.get("statusCode")
            
            # Make the API request
            response = api_client.get(ENDPOINT)
            
            # Validate status code matches expected
            assert response.status_code == expected_status, (
                f"Scenario: {scenario} - "
                f"Expected status code {expected_status}, got {response.status_code}. "
                f"Response: {response.text}"
            )
            
            # Validate response schema for successful responses
            if expected_status == 200:
                validation_result = schema_validator.validate_schema_by_response(
                    ENDPOINT, HTTP_METHOD, str(expected_status), response
                )
                assert validation_result["valid"], (
                    f"Scenario: {scenario} - "
                    f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
                )


class TestListClustersResponseValidation:
    """Tests for response validation and edge cases"""
    
    def test_response_content_type(self, api_client):
        """Test that response has appropriate content type"""
        response = api_client.get(ENDPOINT)
        
        assert response.status_code == 200
        
        content_type = response.headers.get("Content-Type", "")
        assert "application/json" in content_type.lower() or "json" in content_type.lower(), (
            f"Expected JSON content type, got: {content_type}"
        )
    
    def test_empty_array_response_valid(self, api_client, schema_validator):
        """Test that an empty array response is valid per schema"""
        response = api_client.get(ENDPOINT)
        
        assert response.status_code == 200
        
        # Empty array should be valid per the schema (array with no items)
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed for response: {validation_result.get('message')}"
        )
    
    def test_response_headers_present(self, api_client):
        """Test that response contains expected headers"""
        response = api_client.get(ENDPOINT)
        
        assert response.status_code == 200
        assert "Content-Type" in response.headers, "Content-Type header should be present"


class TestListClustersMissingAuth:
    """Tests for missing authentication scenarios"""
    
    def test_missing_auth_token(self, api_host):
        """
        Test API behavior when authentication token is missing.
        
        Note: The actual response code depends on API implementation.
        This test documents the behavior without the auth token.
        """
        import requests
        
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        
        # Make request without auth token
        response = requests.get(url, timeout=30)
        
        # API should return an error status (typically 401 or 403)
        # We don't assert specific code as it depends on implementation
        # but we document the behavior
        assert response.status_code in [200, 401, 403], (
            f"Unexpected status code {response.status_code} for missing auth. "
            f"Response: {response.text}"
        )
    
    def test_invalid_auth_token(self, api_host):
        """
        Test API behavior with invalid authentication token.
        
        Uses a clearly invalid token to test authentication handling.
        """
        import requests
        
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        headers = {"x-auth-token": "invalid-token-12345"}
        
        response = requests.get(url, headers=headers, timeout=30)
        
        # API should reject invalid token (typically 401 or 403)
        assert response.status_code in [200, 401, 403], (
            f"Unexpected status code {response.status_code} for invalid auth. "
            f"Response: {response.text}"
        )
    
    def test_empty_auth_token(self, api_host):
        """
        Test API behavior with empty authentication token.
        """
        import requests
        
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        headers = {"x-auth-token": ""}
        
        response = requests.get(url, headers=headers, timeout=30)
        
        # API should handle empty token appropriately
        assert response.status_code in [200, 401, 403], (
            f"Unexpected status code {response.status_code} for empty auth. "
            f"Response: {response.text}"
        )


class TestListClustersEdgeCases:
    """Edge case and boundary tests"""
    
    def test_trailing_slash_endpoint(self, api_client, schema_validator):
        """Test endpoint with trailing slash"""
        response = api_client.get("/api/v1/clusters/")
        
        assert response.status_code == 200
        
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"]
    
    def test_no_trailing_slash_endpoint(self, api_client):
        """Test endpoint without trailing slash"""
        response = api_client.get("/api/v1/clusters")
        
        # API may redirect or handle both formats
        assert response.status_code in [200, 301, 302, 307, 308], (
            f"Unexpected status code {response.status_code} for endpoint without trailing slash"
        )
    
    def test_case_sensitivity(self, api_host, keystone_token):
        """Test that endpoint path is case-sensitive"""
        import requests
        
        url = f"{api_host.rstrip('/')}/api/v1/CLUSTERS/"
        headers = {"x-auth-token": keystone_token} if keystone_token else {}
        
        response = requests.get(url, headers=headers, timeout=30)
        
        # Most REST APIs are case-sensitive, expect 404 for wrong case
        # But some may be case-insensitive
        assert response.status_code in [200, 404], (
            f"Unexpected status code {response.status_code} for case variation"
        )
    
    def test_extra_query_parameters_ignored(self, api_client, schema_validator):
        """Test that extra query parameters are handled gracefully"""
        response = api_client.get(ENDPOINT, params={"unknown_param": "value"})
        
        # API should either ignore unknown params or return appropriate error
        assert response.status_code in [200, 400], (
            f"Unexpected status code {response.status_code} for extra query params"
        )
        
        if response.status_code == 200:
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, HTTP_METHOD, "200", response
            )
            assert validation_result["valid"]


class TestListClustersMethodValidation:
    """Tests for HTTP method validation"""
    
    def test_post_method_not_allowed(self, api_client):
        """Test that POST method returns appropriate error"""
        response = api_client.post(ENDPOINT, json={})
        
        # POST should not be allowed on this endpoint
        assert response.status_code in [405, 404, 400, 401], (
            f"Expected method not allowed error, got {response.status_code}"
        )
    
    def test_put_method_not_allowed(self, api_client):
        """Test that PUT method returns appropriate error"""
        response = api_client.put(ENDPOINT, json={})
        
        assert response.status_code in [405, 404, 400, 401], (
            f"Expected method not allowed error, got {response.status_code}"
        )
    
    def test_delete_method_not_allowed(self, api_client):
        """Test that DELETE method returns appropriate error"""
        response = api_client.delete(ENDPOINT)
        
        assert response.status_code in [405, 404, 400, 401], (
            f"Expected method not allowed error, got {response.status_code}"
        )
    
    def test_patch_method_not_allowed(self, api_client):
        """Test that PATCH method returns appropriate error"""
        response = api_client.patch(ENDPOINT, json={})
        
        assert response.status_code in [405, 404, 400, 401], (
            f"Expected method not allowed error, got {response.status_code}"
        )
