# ********RoostGPT********

# Test generated by RoostGPT for test API-test-yaml using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /api/v1/clusters/_post for http method type POST 
# RoostTestHash=c655209eb9
# 
# 

# ********RoostGPT********
"""
Test Suite for POST /api/v1/clusters/ - Create Cluster API

This module contains comprehensive pytest tests for the CreateCluster endpoint.
Tests cover successful cluster creation, validation errors, and edge cases.

Setup:
    1. Ensure config.yml is properly configured with API host and auth token
    2. Set environment variables: API_HOST, x-auth-token
    3. Run tests: pytest test_api_v1_clusters.py -v

Endpoints Tested:
    - POST /api/v1/clusters/ - Create a cluster

Security Schema:
    - keystone: Token-based authentication via x-auth-token header
"""

import json
import os
from pathlib import Path

import pytest

from validator import SwaggerSchemaValidator


# Load test data from JSON file
def load_endpoint_test_data():
    """Load test data from api_v1_clusters.json file"""
    test_file = Path(__file__).parent / "api_v1_clusters.json"
    if test_file.exists():
        with open(test_file, "r") as f:
            return json.load(f)
    return []


ENDPOINT_TEST_DATA = load_endpoint_test_data()
ENDPOINT = "/api/v1/clusters/"
METHOD = "post"


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize SwaggerSchemaValidator with API spec"""
    spec_path = Path(__file__).parent / "api.json"
    return SwaggerSchemaValidator(str(spec_path))


@pytest.fixture(scope="function")
def merged_test_data(config_test_data):
    """
    Fixture to provide merged test data.
    Combines config_test_data with scenario-specific data.
    """
    def _merge(scenario_data):
        """Merge config test data with scenario-specific data"""
        merged = dict(config_test_data)
        if scenario_data:
            merged.update(scenario_data)
        return merged
    return _merge


class TestCreateClusterSuccess:
    """Test cases for successful cluster creation scenarios"""

    @pytest.mark.smoke
    def test_create_cluster_with_required_fields(
        self, api_client, config_test_data, schema_validator
    ):
        """
        Test successful cluster creation with only required fields.
        
        This is a happy path test that validates the API accepts
        a valid request body and returns 200 OK.
        """
        # Build request body from config test data (required fields only)
        request_body = {}
        if config_test_data.get("name"):
            request_body["name"] = config_test_data.get("name")
        
        # Make API request
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Assert status code
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, METHOD, "200", response
        )
        assert validation_result["valid"], (
            f"Response schema validation failed: {validation_result.get('message')}"
        )

    @pytest.mark.smoke
    @pytest.mark.parametrize(
        "test_case",
        [tc for tc in ENDPOINT_TEST_DATA if tc.get("statusCode") == 200],
        ids=lambda tc: tc.get("scenario", "unknown_scenario")
    )
    def test_create_cluster_success_scenarios(
        self, api_client, config_test_data, schema_validator, test_case, merged_test_data
    ):
        """
        Test successful cluster creation with various valid payloads.
        
        Uses table-driven testing from api_v1_clusters.json for 200 status scenarios.
        """
        # Merge config test data with scenario-specific body
        scenario_body = test_case.get("body", {})
        merged_data = merged_test_data(scenario_body)
        
        # Build request body - use merged data
        request_body = {}
        if merged_data.get("name"):
            request_body["name"] = merged_data.get("name")
        elif scenario_body.get("name"):
            request_body["name"] = scenario_body.get("name")
        
        # Make API request
        response = api_client.post(ENDPOINT, json=request_body)
        
        expected_status = test_case.get("statusCode")
        assert response.status_code == expected_status, (
            f"Scenario: {test_case.get('scenario')}. "
            f"Expected {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema for success responses
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, METHOD, str(expected_status), response
        )
        assert validation_result["valid"], (
            f"Response schema validation failed for scenario '{test_case.get('scenario')}': "
            f"{validation_result.get('message')}"
        )


class TestCreateClusterTableDriven:
    """Table-driven tests using data from api_v1_clusters.json"""

    @pytest.mark.parametrize(
        "test_case",
        ENDPOINT_TEST_DATA,
        ids=lambda tc: f"{tc.get('scenario', 'unknown')}_{tc.get('statusCode', 'unknown')}"
    )
    def test_create_cluster_all_scenarios(
        self, api_client, config_test_data, schema_validator, test_case, merged_test_data
    ):
        """
        Test cluster creation with all scenarios from test data file.
        
        Iterates through all test cases in api_v1_clusters.json and validates
        each scenario against expected status code and response schema.
        """
        scenario_body = test_case.get("body", {})
        merged_data = merged_test_data(scenario_body)
        
        # Build request body from merged data
        request_body = {}
        if merged_data.get("name"):
            request_body["name"] = merged_data.get("name")
        elif scenario_body.get("name"):
            request_body["name"] = scenario_body.get("name")
        # Include other fields from scenario body
        for key, value in scenario_body.items():
            if key not in request_body:
                request_body[key] = value
        
        # Make API request
        response = api_client.post(ENDPOINT, json=request_body)
        
        expected_status = test_case.get("statusCode")
        assert response.status_code == expected_status, (
            f"Scenario: {test_case.get('scenario')}. "
            f"Expected {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, METHOD, str(expected_status), response
        )
        assert validation_result["valid"], (
            f"Response schema validation failed for scenario '{test_case.get('scenario')}': "
            f"{validation_result.get('message')}"
        )


class TestCreateClusterValidation:
    """Test cases for request validation and edge cases"""

    def test_create_cluster_empty_body(self, api_client, schema_validator):
        """
        Test cluster creation with empty request body.
        
        The API spec defines body as required, so empty body should
        still be accepted as the schema allows empty object.
        """
        request_body = {}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Empty body may be valid since 'name' is not marked as required in schema
        # The API should return 200 or a validation error
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for empty body, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        if response.status_code == 200:
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, METHOD, "200", response
            )
            assert validation_result["valid"], (
                f"Response schema validation failed: {validation_result.get('message')}"
            )

    def test_create_cluster_with_null_name(self, api_client, schema_validator):
        """
        Test cluster creation with null name value.
        
        Tests edge case where name field is explicitly set to null.
        """
        request_body = {"name": None}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Null value may be rejected or accepted depending on API implementation
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for null name, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_create_cluster_with_empty_string_name(self, api_client, schema_validator):
        """
        Test cluster creation with empty string name.
        
        Tests boundary condition for name field.
        """
        request_body = {"name": ""}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Empty string may be valid or invalid depending on API validation
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for empty string name, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_create_cluster_with_special_characters_name(
        self, api_client, config_test_data, schema_validator
    ):
        """
        Test cluster creation with special characters in name.
        
        Tests edge case for name field with special characters.
        """
        request_body = {"name": "test-cluster_123!@#"}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Special characters may or may not be allowed
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_create_cluster_with_very_long_name(self, api_client, schema_validator):
        """
        Test cluster creation with very long name string.
        
        Tests boundary condition for maximum name length.
        """
        # Generate a very long name (1000 characters)
        long_name = "a" * 1000
        request_body = {"name": long_name}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Long name may be truncated, rejected, or accepted
        assert response.status_code in [200, 400, 413], (
            f"Expected 200, 400, or 413 for long name, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_create_cluster_with_unicode_name(self, api_client, schema_validator):
        """
        Test cluster creation with unicode characters in name.
        
        Tests internationalization support for name field.
        """
        request_body = {"name": "集群测试-クラスター-кластер"}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Unicode may or may not be supported
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for unicode name, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_create_cluster_with_extra_fields(
        self, api_client, config_test_data, schema_validator
    ):
        """
        Test cluster creation with additional unexpected fields.
        
        Tests API behavior when extra fields are included in request.
        """
        request_body = {
            "name": config_test_data.get("name", "test-cluster"),
            "unexpected_field": "unexpected_value",
            "another_extra": 12345
        }
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Extra fields may be ignored or cause an error
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for extra fields, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_create_cluster_with_wrong_type_name(self, api_client, schema_validator):
        """
        Test cluster creation with wrong type for name field.
        
        Tests type validation - name should be string but sending integer.
        """
        request_body = {"name": 12345}
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        # Wrong type should be rejected
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for wrong type, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestCreateClusterResponseValidation:
    """Test cases focusing on response validation"""

    def test_response_contains_name_field(
        self, api_client, config_test_data, schema_validator
    ):
        """
        Test that successful response contains name field as per schema.
        
        Validates response structure matches OpenAPI specification.
        """
        request_body = {}
        if config_test_data.get("name"):
            request_body["name"] = config_test_data.get("name")
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        if response.status_code == 200:
            # Validate response schema
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, METHOD, "200", response
            )
            assert validation_result["valid"], (
                f"Response schema validation failed: {validation_result.get('message')}"
            )
            
            # Check response is valid JSON
            try:
                response_json = response.json()
                assert isinstance(response_json, dict), "Response should be an object"
            except json.JSONDecodeError:
                pytest.fail("Response is not valid JSON")

    def test_response_content_type(self, api_client, config_test_data):
        """
        Test that response has correct content type header.
        """
        request_body = {}
        if config_test_data.get("name"):
            request_body["name"] = config_test_data.get("name")
        
        response = api_client.post(ENDPOINT, json=request_body)
        
        if response.status_code == 200:
            content_type = response.headers.get("Content-Type", "")
            assert "application/json" in content_type or response.text == "", (
                f"Expected JSON content type, got: {content_type}"
            )
