# ********RoostGPT********
"""
Test generated by RoostGPT for test demo-python using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=Bill_App.total_ee3e9fb67f
ROOST_METHOD_SIG_HASH=Bill_App.total_11f4f7312f


Scenario 1: Zero quantities across all categories produce zero totals, zero taxes, and zero overall bill
Details:
  TestName: test_total_all_zero_quantities
  Description: Verifies that when all item quantities are set to 0, each category total is 0.0, each tax is 0.0, and the overall total_bill is 0.0. Also confirms the "Rs. " string formatting for display variables reflects 0.0.
Execution:
  Arrange: Initialize a Tk root and a Bill_App instance (e.g., root = Tk(); app = Bill_App(root)). Set all quantity variables (hand_gloves, sanitizer, mask, dettol, newsprin, thermal_gun, rice, food_oil, wheat, daal, flour, maggi, sprite, limka, mazza, coke, fanta, mountain_duo) to 0.
  Act: Invoke app.total().
  Assert: 
    - app.total_medical_price == 0.0 and app.medical_price.get() == "Rs. 0.0"
    - app.c_tax == 0.0 and app.medical_tax.get() == "Rs. 0.0"
    - app.total_grocery_price == 0.0 and app.grocery_price.get() == "Rs. 0.0"
    - app.g_tax == 0.0 and app.grocery_tax.get() == "Rs. 0.0"
    - app.total_cold_drinks_price == 0.0 and app.cold_drinks_price.get() == "Rs. 0.0"
    - app.c_d_tax == 0.0 and app.cold_drinks_tax.get() == "Rs. 0.0"
    - app.total_bill == 0.0
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements. This validates the neutral baseline behavior, ensures no residual state influences new calculations, and confirms the string formatting and numeric fields correctly represent zero totals and taxes.

"""

# ********RoostGPT********
import pytest
from tkinter import *
import random
import os
from tkinter import messagebox
from projects.Billing_system.biling_system import Bill_App


class Test_BillAppTotal:
    @pytest.fixture
    def app_and_root(self):
        # Attempt to create the Tk root window; skip tests if not possible (e.g., headless without display)
        try:
            root = Tk()
            root.withdraw()  # Avoid displaying any GUI during tests
        except Exception as e:
            pytest.skip(f"Skipping tests because Tk could not be initialized: {e}")

        # Initialize the application instance
        app = Bill_App(root)

        yield app, root

        # Teardown
        try:
            root.destroy()
        except Exception:
            pass

    @pytest.mark.smoke
    @pytest.mark.regression
    @pytest.mark.positive
    @pytest.mark.valid
    def test_total_all_zero_quantities(self, app_and_root):
        app, root = app_and_root

        # Arrange: Set all quantities to zero
        # // TODO: If your environment lacks a display, configure a virtual display or adjust Tk initialization accordingly.
        app.hand_gloves.set(0)
        app.sanitizer.set(0)
        app.mask.set(0)
        app.dettol.set(0)
        app.newsprint = getattr(app, "newsprin", None)  # safeguard in case of naming mismatch
        if app.newsprint is not None:
            app.newsprint.set(0)
        else:
            app.newsprin.set(0)

        app.thermal_gun.set(0)

        app.rice.set(0)
        app.food_oil.set(0)
        app.wheat.set(0)
        app.daal.set(0)
        app.flour.set(0)
        app.maggi.set(0)

        app.sprite.set(0)
        app.limka.set(0)
        app.mazza.set(0)
        app.coke.set(0)
        app.fanta.set(0)
        app.mountain_duo.set(0)

        # Act: Invoke total calculation
        app.total()

        # Assert: Medical category totals and taxes are zero and correctly formatted
        assert app.total_medical_price == 0.0
        assert app.medical_price.get() == "Rs. 0.0"
        assert app.c_tax == 0.0
        assert app.medical_tax.get() == "Rs. 0.0"

        # Assert: Grocery category totals and taxes are zero and correctly formatted
        assert app.total_grocery_price == 0.0
        assert app.grocery_price.get() == "Rs. 0.0"
        assert app.g_tax == 0.0
        assert app.grocery_tax.get() == "Rs. 0.0"

        # Assert: Cold drinks category totals and taxes are zero and correctly formatted
        assert app.total_cold_drinks_price == 0.0
        assert app.cold_drinks_price.get() == "Rs. 0.0"
        assert app.c_d_tax == 0.0
        assert app.cold_drinks_tax.get() == "Rs. 0.0"

        # Assert: Overall bill is zero
        assert app.total_bill == 0.0

        # Validation rationale (comment):
        # This test ensures the baseline scenario produces neutral outputs with zeroed quantities, confirming
        # that no residual state affects calculations and that both numeric and display string fields reflect 0.0 correctly.