# ********RoostGPT********
"""
Test generated by RoostGPT for test demo-python using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=Bill_App.clear_data_039b9b5ff8
ROOST_METHOD_SIG_HASH=Bill_App.clear_data_75709990c7


Scenario 1: Confirming clear resets all quantities, prices, taxes, customer info, and search field; generates a new bill number; and refreshes the bill text.
Details:
  TestName: test_clear_data_confirm_resets_state_and_updates_bill_text
  Description: Verify that when the user confirms the clear operation, all item quantities (medical, grocery, cold-drinks) are set to 0; all price and tax fields are set to empty strings; customer name and phone are cleared; search_bill is cleared; bill_no is replaced by a new 4-digit random string; and welcome_bill refreshes the text area with the expected header and values.
Execution:
  Arrange: Instantiate Bill_App with a Tk root and withdraw the window. Pre-set quantities to non-zero values (e.g., sanitizer=5, mask=3, rice=2, sprite=7, etc.), prices/taxes to non-empty strings (e.g., "100.50"), customer fields to non-empty strings (e.g., c_name="Alice", c_phone="9999999999"), search_bill="INV-123". Set bill_no="OLD-001". Monkeypatch messagebox.askyesno to return True and random.randint to return 1234.
  Act: Call obj.clear_data().
  Assert: All quantities report 0 via .get(); price/tax fields report ""; c_name and c_phone are ""; search_bill is ""; bill_no is "1234". The text area content starts with "Welcome Webcode Retail", includes "Bill Number:1234", "Customer Name:", "Phone Number", a separator line of "================================", and a "Products\t\tQTY\t\tPrice" header. Ensure content was cleared/replaced (top of text is the welcome header).
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: This validates the core business logic of clearing transaction state and producing a fresh bill presentation. It ensures users start from a clean slate after confirmation and that the UI reflects the cleared state.

Scenario 2: Canceling clear leaves all state unchanged and does not update the bill text.
Details:
  TestName: test_clear_data_cancel_does_not_change_state
  Description: Verify that when the user cancels, none of the variables or the text area changes, and welcome_bill is not invoked.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Pre-set representative non-default values across quantities, prices, taxes, customer fields, search_bill, and bill_no. Capture current text area content. Monkeypatch messagebox.askyesno to return False.
  Act: Call obj.clear_data().
  Assert: All variables remain unchanged compared to their pre-call values; bill_no remains the same; search_bill unchanged; text area content is unchanged. Confirm welcome_bill was not called (via spy or call-count assertion).
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Ensures user intent is respected and no accidental data loss occurs when the user declines the clear operation.

Scenario 3: Bill number is generated within the specified bounds and set as a string.
Details:
  TestName: test_clear_data_bill_number_generation_bounds_and_type
  Description: Validate that random.randint is called with (1000, 9999), and the bill number assigned is a string matching the returned integer.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Monkeypatch messagebox.askyesno to True. Monkeypatch random.randint to return 9876 and track call arguments.
  Act: Call obj.clear_data().
  Assert: random.randint called exactly once with (1000, 9999). bill_no.get() equals "9876" and is type string.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Confirms compliance with the business rule for bill number format and ensures UI methods relying on string interpolation will work correctly.

Scenario 4: welcome_bill integration after clear produces consistent, structured bill header lines.
Details:
  TestName: test_clear_data_calls_welcome_bill_and_structures_txtarea
  Description: Verify the text area content format after clear by checking deletion and insertion of expected header lines and dynamic values.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Pre-set c_name="Bob", c_phone="1234567890". Monkeypatch askyesno to True and random.randint to return 5555. Optionally pre-fill text area with junk content to ensure it gets cleared.
  Act: Call obj.clear_data().
  Assert: Text area content begins with "Welcome Webcode Retail". Subsequent lines include "Bill Number:5555", "Customer Name:", "Phone Number1234567890" (note phone line has no colon per provided code), "================================", and "Products\t\tQTY\t\tPrice". Verify that previous junk content is removed.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Validates UI consistency and correctness of the bill layout, critical for user readability and downstream printing/export.

Scenario 5: Clearing resets all individual item quantities regardless of their starting values.
Details:
  TestName: test_clear_data_resets_all_item_quantities_to_zero
  Description: Ensure every item quantity (medical: sanitizer, mask, hand_gloves, dettol, newsprin, thermal_gun; grocery: rice, food_oil, wheat, daal, flour, maggi; cold drinks: sprite, limka, mazza, coke, fanta, mountain_duo) is set to 0 after confirmation.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Set each item quantity to varied non-zero values, including edge cases like negative (-1) or large (999). Monkeypatch askyesno to True.
  Act: Call obj.clear_data().
  Assert: For each listed quantity, .get() equals 0 exactly.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Ensures comprehensive reset of all purchasable item counts, preventing stale or incorrect totals in subsequent billing.

Scenario 6: Clearing resets all price and tax fields to empty strings.
Details:
  TestName: test_clear_data_resets_pricing_and_tax_fields_to_empty_strings
  Description: Validate that medical_price, grocery_price, cold_drinks_price, and their corresponding tax fields are set to "" instead of numeric zeros.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Pre-set price and tax fields to representative non-empty values like "100", "45.75", or computed totals. Monkeypatch askyesno to True.
  Act: Call obj.clear_data().
  Assert: Each price and tax field .get() equals "".
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Confirms differentiation between cleared (no value) and zeroed numeric fields, which may affect UI formatting and downstream calculations.

Scenario 7: Customer fields and search field cleared; bill number replaced.
Details:
  TestName: test_clear_data_resets_customer_and_search_fields_and_regenerates_bill_number
  Description: Ensure c_name, c_phone, search_bill become empty strings, and bill_no becomes a new 4-digit string.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Set c_name="Charlie", c_phone="8888888888", search_bill="B-2024-09", bill_no="B-OLD". Monkeypatch askyesno=True and random.randint=4321.
  Act: Call obj.clear_data().
  Assert: c_name.get()==""; c_phone.get()==""; search_bill.get()==""; bill_no.get()=="4321".
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Ensures both customer metadata and search context are cleared, avoiding accidental carryover between bills.

Scenario 8: Idempotency across consecutive confirmations with changing bill numbers.
Details:
  TestName: test_clear_data_idempotency_on_multiple_confirmations
  Description: Validate that repeated confirmed clear operations keep all fields cleared while generating a fresh bill number and re-rendering the text area each time.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Monkeypatch askyesno to True. Monkeypatch random.randint to return 1111 on first call and 2222 on second. Pre-set some values before the first call; leave them as-is for the second call.
  Act: Call obj.clear_data(); then call obj.clear_data() again.
  Assert: After first call: fields cleared and bill_no=="1111"; text area header shows "Bill Number:1111". After second call: fields still cleared and bill_no=="2222"; text area header updates to "Bill Number:2222".
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Confirms stable behavior and prevents state leakage over multiple resets, a common user scenario.

Scenario 9: No side effects when canceled after a previous confirm.
Details:
  TestName: test_clear_data_cancel_after_confirm_leaves_state_unchanged
  Description: After a successful clear, a subsequent cancel should leave the cleared state unchanged and not regenerate the bill number.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Monkeypatch askyesno to True and random.randint to 3000 for the first call; then monkeypatch askyesno to False for the second call. Perform an initial clear to reach a known cleared state.
  Act: Call obj.clear_data() (confirm); then call obj.clear_data() (cancel).
  Assert: After cancel, all fields remain as after the first clear; bill_no remains "3000"; text area content remains unchanged from the first clear.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Ensures predictability in user workflows and prevents unintended changes on cancel.

Scenario 10: askyesno invoked exactly once with the correct title and prompt.
Details:
  TestName: test_clear_data_confirmation_prompt_invocation_and_message
  Description: Verify that the confirmation dialog is shown with title "Clear" and message "Do you really want to Clear?" and is called exactly once per clear_data invocation.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Monkeypatch messagebox.askyesno to a stub that records calls and returns True.
  Act: Call obj.clear_data().
  Assert: askyesno called once with ("Clear", "Do you really want to Clear?").
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Confirms the presence of a safety check guarding destructive actions, aligning with UX and data integrity expectations.

Scenario 11: Text area is deleted before welcome content is inserted.
Details:
  TestName: test_clear_data_txtarea_cleared_before_welcome_content
  Description: Ensure that welcome_bill deletes existing content, avoiding accumulated or duplicated headers.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Insert multiple lines into txtarea that are not part of the welcome header. Monkeypatch askyesno to True and random.randint=2468.
  Act: Call obj.clear_data().
  Assert: The final content does not contain any of the previously inserted lines; only the welcome header and expected lines are present with the current bill number and customer info.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Guarantees that the displayed bill is clean and readable, preventing user confusion from leftover content.

Scenario 12: Mixed initial values are properly cleared to the specified defaults.
Details:
  TestName: test_clear_data_mixed_initial_values_cleared_to_defaults
  Description: Validate clearing behavior from a mix of starting values: zero/empty, non-zero/non-empty, negative, and large values.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Set sanitizer=0, rice=50, mazza=-3, mountain_duo=999, medical_tax="5.5", grocery_price="", c_name="", c_phone="555". Set search_bill="to-find". Monkeypatch askyesno=True and random.randint=1357.
  Act: Call obj.clear_data().
  Assert: All quantities become 0; price/tax fields become ""; c_name and c_phone become ""; search_bill becomes ""; bill_no becomes "1357". Text area header reflects empty customer info and new bill number.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Confirms robustness of the reset logic across heterogeneous starting states.

Scenario 13: No welcome_bill call and no text area modifications when canceled.
Details:
  TestName: test_clear_data_cancel_does_not_call_welcome_bill_or_change_txtarea
  Description: Independent verification that the text area remains untouched when askyesno returns False.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Insert known marker text into txtarea. Monkeypatch askyesno=False. Optionally spy on welcome_bill call count.
  Act: Call obj.clear_data().
  Assert: The marker text remains in txtarea; welcome_bill was not called; no variables changed.
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Reinforces that UI state is preserved on user cancellation.

Scenario 14: Verification that randomization yields a bill number different from the prior when the random value differs.
Details:
  TestName: test_clear_data_bill_number_changes_from_previous_on_confirm
  Description: Ensure the newly generated bill number replaces the previous bill number when confirmation is True.
Execution:
  Arrange: Instantiate Bill_App, withdraw root. Set bill_no="9999". Monkeypatch askyesno=True and random.randint=1234.
  Act: Call obj.clear_data().
  Assert: bill_no.get()=="1234" and not equal to "9999".
Validation:
  Rationalize the importance of the test and the connection of the expected result to the function's specifications and business requirements: Confirms that each cleared session gets a new unique identifier, important for traceability and billing separation.

"""

# ********RoostGPT********
import pytest
import importlib
import re
from tkinter import *
import random
import os
from tkinter import messagebox

# // TODO: If the import path is different in your project structure, update it accordingly.
from projects.Billing_system.biling_system import Bill_App


def _make_app_or_skip():
    try:
        root = Tk()
    except Exception as ex:
        pytest.skip(f"Tkinter not available or cannot create root: {ex}")
    root.withdraw()
    app = Bill_App(root)
    return app, root


class Test_BillAppClearData:

    @pytest.mark.smoke
    @pytest.mark.positive
    @pytest.mark.regression
    def test_clear_data_confirm_resets_state_and_updates_bill_text(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            # Pre-set quantities
            app.sanitizer.set(5)
            app.mask.set(3)
            app.hand_gloves.set(10)
            app.dettol.set(4)
            app.newsprin.set(6)
            app.thermal_gun.set(2)

            app.rice.set(2)
            app.food_oil.set(7)
            app.wheat.set(1)
            app.daal.set(8)
            app.flour.set(9)
            app.maggi.set(5)

            app.sprite.set(7)
            app.limka.set(2)
            app.mazza.set(3)
            app.coke.set(11)
            app.fanta.set(12)
            app.mountain_duo.set(13)

            # Pre-set price/taxes
            app.medical_price.set("100.50")
            app.grocery_price.set("200")
            app.cold_drinks_price.set("300.00")

            app.medical_tax.set("5")
            app.grocery_tax.set("10.5")
            app.cold_drinks_tax.set("15")

            # Pre-set customer, search, bill no
            app.c_name.set("Alice")
            app.c_phone.set("9999999999")
            app.search_bill.set("INV-123")
            app.bill_no.set("OLD-001")

            # Patch askyesno to confirm and randint to deterministic value
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            called_args = []

            def fake_randint(a, b):
                called_args.append((a, b))
                return 1234

            monkeypatch.setattr(mod.random, "randint", fake_randint)

            # Pre-fill txtarea with some content to ensure it gets replaced
            app.txtarea.delete('1.0', END)
            app.txtarea.insert(END, "junk before clear")

            app.clear_data()

            # Assert quantities are zero
            assert app.sanitizer.get() == 0
            assert app.mask.get() == 0
            assert app.hand_gloves.get() == 0
            assert app.dettol.get() == 0
            assert app.newsprin.get() == 0
            assert app.thermal_gun.get() == 0

            assert app.rice.get() == 0
            assert app.food_oil.get() == 0
            assert app.wheat.get() == 0
            assert app.daal.get() == 0
            assert app.flour.get() == 0
            assert app.maggi.get() == 0

            assert app.sprite.get() == 0
            assert app.limka.get() == 0
            assert app.mazza.get() == 0
            assert app.coke.get() == 0
            assert app.fanta.get() == 0
            assert app.mountain_duo.get() == 0

            # Assert price/tax fields empty
            assert app.medical_price.get() == ""
            assert app.grocery_price.get() == ""
            assert app.cold_drinks_price.get() == ""
            assert app.medical_tax.get() == ""
            assert app.grocery_tax.get() == ""
            assert app.cold_drinks_tax.get() == ""

            # Assert customer info cleared
            assert app.c_name.get() == ""
            assert app.c_phone.get() == ""
            # search cleared
            assert app.search_bill.get() == ""
            # bill no updated
            assert app.bill_no.get() == "1234"

            # Validate text area structure
            content = app.txtarea.get('1.0', END)
            # Top of text is welcome header (allow for leading whitespace like \t)
            assert app.txtarea.get('1.0', '1.end').lstrip().startswith("Welcome Webcode Retail")
            assert "Bill Number:1234" in content
            assert "Customer Name:" in content
            assert "Phone Number" in content  # no colon per given code
            assert "================================" in content
            assert "Products\t\tQTY\t\tPrice" in content
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.negative
    @pytest.mark.regression
    def test_clear_data_cancel_does_not_change_state(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)

            # Pre-set various fields to non-default values
            app.sanitizer.set(9)
            app.mask.set(8)
            app.hand_gloves.set(7)
            app.dettol.set(6)
            app.newsprin.set(5)
            app.thermal_gun.set(4)

            app.rice.set(3)
            app.food_oil.set(2)
            app.wheat.set(1)
            app.daal.set(11)
            app.flour.set(12)
            app.maggi.set(13)

            app.sprite.set(14)
            app.limka.set(15)
            app.mazza.set(16)
            app.coke.set(17)
            app.fanta.set(18)
            app.mountain_duo.set(19)

            app.medical_price.set("110")
            app.grocery_price.set("220")
            app.cold_drinks_price.set("330")
            app.medical_tax.set("1.1")
            app.grocery_tax.set("2.2")
            app.cold_drinks_tax.set("3.3")

            app.c_name.set("CancelCase")
            app.c_phone.set("1231231234")
            app.search_bill.set("SEARCH-KEEP")
            app.bill_no.set("KEEP-001")

            # Capture pre-call state
            pre_state = {
                "sanitizer": app.sanitizer.get(),
                "mask": app.mask.get(),
                "hand_gloves": app.hand_gloves.get(),
                "dettol": app.dettol.get(),
                "newsprin": app.newsprin.get(),
                "thermal_gun": app.thermal_gun.get(),
                "rice": app.rice.get(),
                "food_oil": app.food_oil.get(),
                "wheat": app.wheat.get(),
                "daal": app.daal.get(),
                "flour": app.flour.get(),
                "maggi": app.maggi.get(),
                "sprite": app.sprite.get(),
                "limka": app.limka.get(),
                "mazza": app.mazza.get(),
                "coke": app.coke.get(),
                "fanta": app.fanta.get(),
                "mountain_duo": app.mountain_duo.get(),
                "medical_price": app.medical_price.get(),
                "grocery_price": app.grocery_price.get(),
                "cold_drinks_price": app.cold_drinks_price.get(),
                "medical_tax": app.medical_tax.get(),
                "grocery_tax": app.grocery_tax.get(),
                "cold_drinks_tax": app.cold_drinks_tax.get(),
                "c_name": app.c_name.get(),
                "c_phone": app.c_phone.get(),
                "search_bill": app.search_bill.get(),
                "bill_no": app.bill_no.get(),
            }
            app.txtarea.delete('1.0', END)
            app.txtarea.insert(END, "do not change this content")
            before_text = app.txtarea.get('1.0', END)

            # Spy on welcome_bill to ensure it's not invoked
            calls = {"count": 0}

            def spy_welcome():
                calls["count"] += 1
                # Intentionally do not modify txtarea to detect unintended calls

            monkeypatch.setattr(app, "welcome_bill", spy_welcome, raising=True)

            # Cancel dialog
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: False)

            app.clear_data()

            # State unchanged
            post_state = {
                "sanitizer": app.sanitizer.get(),
                "mask": app.mask.get(),
                "hand_gloves": app.hand_gloves.get(),
                "dettol": app.dettol.get(),
                "newsprin": app.newsprin.get(),
                "thermal_gun": app.thermal_gun.get(),
                "rice": app.rice.get(),
                "food_oil": app.food_oil.get(),
                "wheat": app.wheat.get(),
                "daal": app.daal.get(),
                "flour": app.flour.get(),
                "maggi": app.maggi.get(),
                "sprite": app.sprite.get(),
                "limka": app.limka.get(),
                "mazza": app.mazza.get(),
                "coke": app.coke.get(),
                "fanta": app.fanta.get(),
                "mountain_duo": app.mountain_duo.get(),
                "medical_price": app.medical_price.get(),
                "grocery_price": app.grocery_price.get(),
                "cold_drinks_price": app.cold_drinks_price.get(),
                "medical_tax": app.medical_tax.get(),
                "grocery_tax": app.grocery_tax.get(),
                "cold_drinks_tax": app.cold_drinks_tax.get(),
                "c_name": app.c_name.get(),
                "c_phone": app.c_phone.get(),
                "search_bill": app.search_bill.get(),
                "bill_no": app.bill_no.get(),
            }
            assert post_state == pre_state
            after_text = app.txtarea.get('1.0', END)
            assert after_text == before_text
            assert calls["count"] == 0
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.positive
    @pytest.mark.regression
    def test_clear_data_bill_number_generation_bounds_and_type(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            # Ensure confirm
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            calls = []

            def capture_randint(a, b):
                calls.append((a, b))
                return 9876

            monkeypatch.setattr(mod.random, "randint", capture_randint)
            app.clear_data()
            assert len(calls) == 1
            assert calls[0] == (1000, 9999)
            val = app.bill_no.get()
            assert isinstance(val, str)
            assert val == "9876"
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    @pytest.mark.positive
    def test_clear_data_calls_welcome_bill_and_structures_txtarea(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            app.c_name.set("Bob")
            app.c_phone.set("1234567890")
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", lambda a, b: 5555)
            # Pre-fill text area with junk content to verify clearing
            app.txtarea.delete('1.0', END)
            app.txtarea.insert(END, "random junk that should be cleared")

            app.clear_data()

            content = app.txtarea.get('1.0', END)
            assert content.lstrip().startswith("Welcome Webcode Retail")
            assert "Bill Number:5555" in content
            assert "Customer Name:" in content
            # Note: Phone Number has no colon, per provided code
            assert "Phone Number1234567890" in content
            assert "================================" in content
            assert "Products\t\tQTY\t\tPrice" in content
            # Ensure previous junk removed
            assert "random junk that should be cleared" not in content
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    @pytest.mark.positive
    def test_clear_data_resets_all_item_quantities_to_zero(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            # Set varied values, including negative and large
            app.sanitizer.set(-1)
            app.mask.set(999)
            app.hand_gloves.set(3)
            app.dettol.set(1)
            app.newsprin.set(2)
            app.thermal_gun.set(1000)

            app.rice.set(50)
            app.food_oil.set(-3)
            app.wheat.set(999)
            app.daal.set(0)
            app.flour.set(18)
            app.maggi.set(7)

            app.sprite.set(5)
            app.limka.set(6)
            app.mazza.set(-10)
            app.coke.set(0)
            app.fanta.set(123)
            app.mountain_duo.set(999)

            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            app.clear_data()

            for attr in [
                "sanitizer", "mask", "hand_gloves", "dettol", "newsprin", "thermal_gun",
                "rice", "food_oil", "wheat", "daal", "flour", "maggi",
                "sprite", "limka", "mazza", "coke", "fanta", "mountain_duo"
            ]:
                assert getattr(app, attr).get() == 0, f"{attr} not reset to 0"
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    @pytest.mark.positive
    def test_clear_data_resets_pricing_and_tax_fields_to_empty_strings(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            # Pre-set values
            app.medical_price.set("100")
            app.grocery_price.set("45.75")
            app.cold_drinks_price.set("9999")
            app.medical_tax.set("2.5")
            app.grocery_tax.set("1.25")
            app.cold_drinks_tax.set("0")
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)

            app.clear_data()

            assert app.medical_price.get() == ""
            assert app.grocery_price.get() == ""
            assert app.cold_drinks_price.get() == ""
            assert app.medical_tax.get() == ""
            assert app.grocery_tax.get() == ""
            assert app.cold_drinks_tax.get() == ""
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_clear_data_resets_customer_and_search_fields_and_regenerates_bill_number(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            app.c_name.set("Charlie")
            app.c_phone.set("8888888888")
            app.search_bill.set("B-2024-09")
            app.bill_no.set("B-OLD")
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", lambda a, b: 4321)
            app.clear_data()
            assert app.c_name.get() == ""
            assert app.c_phone.get() == ""
            assert app.search_bill.get() == ""
            assert app.bill_no.get() == "4321"
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    @pytest.mark.positive
    def test_clear_data_idempotency_on_multiple_confirmations(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)

            # First confirmation
            seq = {"calls": 0}

            def randint_seq(a, b):
                if seq["calls"] == 0:
                    seq["calls"] += 1
                    return 1111
                return 2222

            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", randint_seq)

            # Pre-set some values before first call
            app.sanitizer.set(10)
            app.medical_price.set("10")
            app.c_name.set("Name")
            app.txtarea.delete('1.0', END)
            app.txtarea.insert(END, "to be cleared once")

            app.clear_data()
            content1 = app.txtarea.get('1.0', END)
            assert app.bill_no.get() == "1111"
            assert content1.find("Bill Number:1111") != -1

            # Call again without touching fields; they should remain cleared
            app.clear_data()
            content2 = app.txtarea.get('1.0', END)
            assert app.bill_no.get() == "2222"
            assert content2.find("Bill Number:2222") != -1

            # Ensure cleared fields remain cleared after both runs
            assert app.sanitizer.get() == 0
            assert app.medical_price.get() == ""
            assert app.c_name.get() == ""
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    @pytest.mark.negative
    def test_clear_data_cancel_after_confirm_leaves_state_unchanged(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)

            # First: confirm clear
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", lambda a, b: 3000)
            app.sanitizer.set(5)
            app.medical_price.set("55")
            app.c_name.set("WillClear")

            app.clear_data()
            after_confirm = {
                "sanitizer": app.sanitizer.get(),
                "medical_price": app.medical_price.get(),
                "c_name": app.c_name.get(),
                "bill_no": app.bill_no.get(),
                "txt": app.txtarea.get('1.0', END),
            }
            assert after_confirm["bill_no"] == "3000"

            # Then: cancel
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: False)
            before_cancel_text = app.txtarea.get('1.0', END)
            app.clear_data()
            after_cancel = {
                "sanitizer": app.sanitizer.get(),
                "medical_price": app.medical_price.get(),
                "c_name": app.c_name.get(),
                "bill_no": app.bill_no.get(),
                "txt": app.txtarea.get('1.0', END),
            }

            assert after_cancel == after_confirm
            assert before_cancel_text == after_cancel["txt"]
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.security
    @pytest.mark.smoke
    def test_clear_data_confirmation_prompt_invocation_and_message(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            calls = []

            def fake_askyesno(title, message):
                calls.append((title, message))
                return True

            monkeypatch.setattr(mod.messagebox, "askyesno", fake_askyesno)
            app.clear_data()
            assert len(calls) == 1
            assert calls[0] == ("Clear", "Do you really want to Clear?")
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    def test_clear_data_txtarea_cleared_before_welcome_content(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            app.txtarea.delete('1.0', END)
            app.txtarea.insert(END, "LINE A\nLINE B\nLINE C\n")
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", lambda a, b: 2468)

            app.clear_data()

            content = app.txtarea.get('1.0', END)
            assert "LINE A" not in content
            assert "LINE B" not in content
            assert "LINE C" not in content
            assert "Welcome Webcode Retail" in content
            assert "Bill Number:2468" in content
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.regression
    @pytest.mark.positive
    def test_clear_data_mixed_initial_values_cleared_to_defaults(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            # Mixed initial values
            app.sanitizer.set(0)
            app.rice.set(50)
            app.mazza.set(-3)
            app.mountain_duo.set(999)
            app.medical_tax.set("5.5")
            app.grocery_price.set("")
            app.c_name.set("")
            app.c_phone.set("555")
            app.search_bill.set("to-find")

            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", lambda a, b: 1357)

            app.clear_data()

            # Quantities are all zero
            for attr in [
                "sanitizer", "mask", "hand_gloves", "dettol", "newsprin", "thermal_gun",
                "rice", "food_oil", "wheat", "daal", "flour", "maggi",
                "sprite", "limka", "mazza", "coke", "fanta", "mountain_duo"
            ]:
                assert getattr(app, attr).get() == 0

            # Prices and taxes empty
            assert app.medical_price.get() == ""
            assert app.grocery_price.get() == ""
            assert app.cold_drinks_price.get() == ""
            assert app.medical_tax.get() == ""
            assert app.grocery_tax.get() == ""
            assert app.cold_drinks_tax.get() == ""

            # Customer and search cleared
            assert app.c_name.get() == ""
            assert app.c_phone.get() == ""
            assert app.search_bill.get() == ""

            # Bill number updated
            assert app.bill_no.get() == "1357"

            # Header reflects empty customer info and new bill number
            content = app.txtarea.get('1.0', END)
            assert "Bill Number:1357" in content
            assert "Customer Name:" in content
            # Phone line contains "Phone Number" and should not include residual "555"
            assert "Phone Number" in content
            assert "Phone Number555" not in content
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.negative
    @pytest.mark.regression
    def test_clear_data_cancel_does_not_call_welcome_bill_or_change_txtarea(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            app.txtarea.delete('1.0', END)
            marker = "DO NOT TOUCH MARKER"
            app.txtarea.insert(END, marker)
            before = app.txtarea.get('1.0', END)

            # Spy on welcome_bill to ensure it is not called
            called = {"count": 0}

            def spy_welcome():
                called["count"] += 1

            monkeypatch.setattr(app, "welcome_bill", spy_welcome, raising=True)
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: False)

            # Set a few variables to verify they don't change
            app.sanitizer.set(42)
            app.medical_price.set("77")
            app.c_name.set("KeepMe")
            app.bill_no.set("SAME")

            app.clear_data()

            after = app.txtarea.get('1.0', END)
            assert before == after
            assert called["count"] == 0
            assert app.sanitizer.get() == 42
            assert app.medical_price.get() == "77"
            assert app.c_name.get() == "KeepMe"
            assert app.bill_no.get() == "SAME"
        finally:
            try:
                root.destroy()
            except Exception:
                pass

    @pytest.mark.positive
    @pytest.mark.regression
    def test_clear_data_bill_number_changes_from_previous_on_confirm(self, monkeypatch):
        app, root = _make_app_or_skip()
        try:
            mod = importlib.import_module(Bill_App.__module__)
            app.bill_no.set("9999")
            monkeypatch.setattr(mod.messagebox, "askyesno", lambda *a, **k: True)
            monkeypatch.setattr(mod.random, "randint", lambda a, b: 1234)
            app.clear_data()
            assert app.bill_no.get() == "1234"
            assert app.bill_no.get() != "9999"
        finally:
            try:
                root.destroy()
            except Exception:
                pass
