# ********RoostGPT********
"""
Test generated by RoostGPT for test demo-python using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=Bill_App.total_ee3e9fb67f
ROOST_METHOD_SIG_HASH=Bill_App.total_11f4f7312f


 
Scenario 1: All quantities are zero, all totals and taxes should be zero
Details:
  TestName: test_total_all_zero_quantities_results_in_zeroes
  Description: Ensures the method computes zero for all category totals, taxes, and overall total when all item quantities are zero.
Execution:
  Arrange: Create a Bill_App-like stub with all quantity variables (hand_gloves, sanitizer, mask, dettol, newsprin, thermal_gun, rice, food_oil, wheat, daal, flour, maggi, sprite, limka, mazza, coke, fanta, mountain_duo) set to 0, and string-holding variables (medical_price, medical_tax, grocery_price, grocery_tax, cold_drinks_price, cold_drinks_tax) ready to capture set() values.
  Act: Call total().
  Assert: 
    - medical_price == "Rs. 0.0" and medical_tax == "Rs. 0.0"
    - grocery_price == "Rs. 0.0" and grocery_tax == "Rs. 0.0" (as implemented, 0 × 5 => 0.0)
    - cold_drinks_price == "Rs. 0.0" and cold_drinks_tax == "Rs. 0.0"
    - total_bill == 0.0
Validation:
  This is the baseline sanity check. With no items purchased, all amounts must be zero, verifying there is no hidden state or unintended default values affecting calculations.

"""

# ********RoostGPT********
import pytest
from tkinter import *
import random
import os
from tkinter import messagebox

from projects.Billing_system.biling_system import Bill_App  # TODO: Adjust import path if module location changes


class Test_BillAppTotal:

    @pytest.mark.smoke
    @pytest.mark.regression
    @pytest.mark.positive
    @pytest.mark.valid
    def test_total_all_zero_quantities_results_in_zeroes(self):
        # Arrange: Create a stub object with required attributes and Var-like behavior
        class DummyVar:
            def __init__(self, initial=None):
                self._value = initial
            def get(self):
                return self._value
            def set(self, val):
                self._value = val

        class BillAppLikeStub:
            pass

        stub = BillAppLikeStub()

        # Input quantity variables set to 0
        zero_quantity_fields = [
            "hand_gloves", "sanitizer", "mask", "dettol", "newsprin", "thermal_gun",
            "rice", "food_oil", "wheat", "daal", "flour", "maggi",
            "sprite", "limka", "mazza", "coke", "fanta", "mountain_duo",
        ]
        for field in zero_quantity_fields:
            setattr(stub, field, DummyVar(0))

        # Output string variables to capture set() values
        output_string_fields = [
            "medical_price", "medical_tax",
            "grocery_price", "grocery_tax",
            "cold_drinks_price", "cold_drinks_tax",
        ]
        for field in output_string_fields:
            setattr(stub, field, DummyVar(""))

        # Act: Invoke the total method from the imported Bill_App class, bound to our stub
        Bill_App.total(stub)

        # Assert: Prices and taxes should all be "Rs. 0.0"
        assert stub.medical_price.get() == "Rs. 0.0"
        assert stub.medical_tax.get() == "Rs. 0.0"
        assert stub.grocery_price.get() == "Rs. 0.0"
        assert stub.grocery_tax.get() == "Rs. 0.0"
        assert stub.cold_drinks_price.get() == "Rs. 0.0"
        assert stub.cold_drinks_tax.get() == "Rs. 0.0"

        # Assert: Total bill should be 0.0
        assert getattr(stub, "total_bill", None) == 0.0