# ********RoostGPT********
"""
Test generated by RoostGPT for test demo-python using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=Bill_App.bill_area_5b1d0eff06
ROOST_METHOD_SIG_HASH=Bill_App.bill_area_2d56362e02


Scenario 1: Block bill generation when customer name or phone is a single space
Details:
  TestName: test_bill_area_blocks_on_single_space_customer_fields
  Description: Verify that if c_name.get() or c_phone.get() returns " " (single space), bill_area shows an error and does not generate or save a bill.
Execution:
  Arrange: 
    - Configure self.c_name.get() -> " " and self.c_phone.get() -> "valid-phone".
    - Set all three category price strings to non-zero values (e.g., "Rs. 10.0") to ensure the "No Product Purchased" branch is not involved.
    - Set at least one product quantity non-zero (e.g., sanitizer=1) and provide required price variables.
    - Stub self.txtarea, self.welcome_bill, and self.save_bill; monkeypatch messagebox.showerror to record calls.
  Act:
    - Call self.bill_area().
  Assert:
    - messagebox.showerror called once with title "Error" and message "Customer Details Are Must".
    - self.welcome_bill not called.
    - self.txtarea receives no new header/item/tax/total insertions.
    - self.save_bill not called.
Validation:
  This ensures mandatory customer details gatekeep bill creation, aligning with the business requirement “Customer Details Are Must”. It also reveals the need for an early return after showing the error.

Scenario 2: Treat empty strings as missing customer details
Details:
  TestName: test_bill_area_blocks_on_empty_customer_fields
  Description: Business expectation is to block when details are effectively missing, including empty strings; current code only checks a single space.
Execution:
  Arrange:
    - self.c_name.get() -> "" and self.c_phone.get() -> "".
    - Set price strings to non-zero (e.g., "Rs. 15.0") and one item quantity non-zero to be sure the validation branch should be the only block.
    - Stub GUI and messagebox as in Scenario 1.
  Act:
    - Call self.bill_area().
  Assert:
    - Expected: showerror and no subsequent header/items/save.
    - If asserting current behavior, this will fail because code does not block empty strings; record as defect.
Validation:
  Validates robust input validation beyond a single-space literal, reflecting realistic data entry and business expectations.

Scenario 3: Block bill generation when no product purchased via price-summary check
Details:
  TestName: test_bill_area_blocks_on_all_zero_price_summaries
  Description: When medical_price, grocery_price, and cold_drinks_price are all "Rs. 0.0", bill creation should be blocked.
Execution:
  Arrange:
    - self.c_name.get() -> "Alice", self.c_phone.get() -> "9876543210".
    - All three price strings -> "Rs. 0.0".
    - All item quantities zero.
    - Stub GUI and messagebox; ensure self.save_bill is spied.
  Act:
    - Call self.bill_area().
  Assert:
    - messagebox.showerror called once with "No Product Purchased".
    - No header/items/taxes/total inserted.
    - self.save_bill not called.
Validation:
  Ensures customers cannot generate/summarize an empty bill, matching the stated error branch.

Scenario 4: Block bill when all quantities are zero even if price summaries are non-zero
Details:
  TestName: test_bill_area_blocks_when_all_quantities_zero_regardless_of_price_strings
  Description: Business logic should block bill creation if no quantities were purchased; current implementation only inspects price strings and may produce a bill with no items.
Execution:
  Arrange:
    - Valid customer details.
    - Set all quantities to 0.
    - Set one or more price strings to non-"Rs. 0.0" values (e.g., "Rs. 50.0").
    - Taxes set to '0.0'; total_bill arbitrary.
  Act:
    - Call self.bill_area().
  Assert:
    - Expected: showerror "No Product Purchased" and abort, with no header/items/total/save.
    - Note: Current code would proceed and generate a bill with no items; record as defect if observed.
Validation:
  Prevents accidental billing without selected items, which is critical for correctness and customer trust.

Scenario 5: Welcome header is written once and clears prior content
Details:
  TestName: test_bill_area_calls_welcome_bill_and_writes_header
  Description: On a valid bill path, bill_area must call welcome_bill to clear the text area and write the header block.
Execution:
  Arrange:
    - Valid customer details and at least one non-zero price summary (not all "Rs. 0.0").
    - Set sanitizer quantity to 1 with a defined self.m_s_p.
    - Taxes set to '0.0'.
    - Implement self.welcome_bill as provided (deletes and inserts header).
  Act:
    - Call self.bill_area().
  Assert:
    - Verify txtarea starts with:
      - "\tWelcome Webcode Retail"
      - " Bill Number:<bill_no>"
      - "Customer Name:<name>"
      - "Phone Number<phone>" (note: no colon before phone per provided code)
      - "================================"
      - "Products\t\tQTY\t\tPrice"
    - Header precedes any item lines.
Validation:
  Confirms structure and ordering of the bill and use of the provided welcome_bill dependency.

Scenario 6: Medical item line formatting and content for sanitizer
Details:
  TestName: test_bill_area_writes_sanitizer_line_correctly
  Description: When sanitizer quantity is non-zero, a correctly formatted line should be inserted with the sanitizer qty and price variable self.m_s_p.
Execution:
  Arrange:
    - Valid customer details.
    - Price summaries not all "Rs. 0.0".
    - Set sanitizer.get() -> 2; all other items 0.
    - self.m_s_p -> a test value (e.g., "Rs. 50").
    - Taxes '0.0'; total_bill any value (e.g., 100).
  Act:
    - Call self.bill_area().
  Assert:
    - txtarea contains "\n Sanitizer\t\t2\t\tRs. 50" once.
    - No other item lines are present.
Validation:
  Validates item-line creation for medical category and verifies the mapping qty->price used by the code.

Scenario 7: Detect mislabeled item lines for mask, limka, coke, fanta, thermal_gun, and mountain_duo
Details:
  TestName: test_bill_area_flags_label_and_quantity_price_mapping_inconsistencies
  Description: Business expectation is that each product is labeled correctly and uses its own quantity and price variables; the current code mislabels several lines or uses wrong quantities.
Execution:
  Arrange:
    - Valid customer details and price summaries not all "Rs. 0.0".
    - Set the following quantities to non-zero:
      - mask=3 (expect label "Mask", price self.m_m_p)
      - thermal_gun=1 (expect label "Thermal Gun" and its own qty; price self.m_t_g_p)
      - limka=2 (expect label "Limka", price self.c_d_l_p)
      - coke=4 (expect label "Coke", price self.c_d_c_p)
      - fanta=5 (expect label "Fanta", qty 5; price self.c_d_f_p)
      - mountain_duo=1 (expect label "Mountain Duo", qty 1; price self.c_m_d)
    - Provide distinct price variables for each.
  Act:
    - Call self.bill_area().
  Assert:
    - Expected business-behavior assertions (should pass if implemented correctly):
      - Lines exist with labels Mask, Thermal Gun, Limka, Coke, Fanta, Mountain Duo.
      - Each line reflects its own quantity (3,1,2,4,5,1 respectively).
    - Under current code, you will observe:
      - Mask line labeled as "Sanitizer".
      - Thermal Gun uses sanitizer quantity instead of thermal_gun quantity.
      - Limka labeled "Sanitizer".
      - Coke labeled "Dettol".
      - Fanta uses newsprin quantity instead of fanta quantity.
      - Mountain Duo uses sanitizer quantity instead of mountain_duo quantity.
    - Record these mismatches as defects.
Validation:
  Ensures correctness, transparency, and customer trust in itemized billing; highlights multiple critical mapping bugs.

Scenario 8: Grocery item line formatting and exclusivity
Details:
  TestName: test_bill_area_writes_grocery_lines_when_quantities_positive_only
  Description: Only grocery items with non-zero quantities should be listed; zero-quantity items should not appear.
Execution:
  Arrange:
    - Valid customer details; prices not all zero.
    - Set rice=1, daal=2; set wheat=0, flour=0, food_oil=0, maggi=0.
    - Provide g_r_p and g_d_p values.
  Act:
    - Call self.bill_area().
  Assert:
    - txtarea has lines:
      - "\n Rice\t\t1\t\t<g_r_p>"
      - "\n Daal\t\t2\t\t<g_d_p>"
    - No lines for wheat, flour, food oil, maggi.
Validation:
  Verifies the conditional inclusion logic per item and avoids clutter/incorrect charges.

Scenario 9: Cold drinks item ordering and separator behavior
Details:
  TestName: test_bill_area_separator_before_taxes_is_consistent
  Description: Business expectation is to separate items from totals/taxes with a consistent line; current code inserts a separator only when mountain_duo quantity is non-zero.
Execution:
  Arrange:
    - Valid customer; price summaries not all zero.
    - Case A: mountain_duo=0, sprite=1; Case B: mountain_duo=1, others 0 (parametrize).
  Act:
    - Call self.bill_area() for both cases.
  Assert:
    - Expected: a separator line appears just before taxes regardless of mountain_duo.
    - Current behavior:
      - Case A: no pre-tax separator.
      - Case B: a separator "\n--------------------------------" appears after Mountain Duo, i.e., before taxes.
    - Mark inconsistency as a defect.
Validation:
  Ensures consistent and readable bill formatting across item selections.

Scenario 10: Taxes are printed only when non-zero and with exact labels
Details:
  TestName: test_bill_area_prints_tax_lines_conditionally
  Description: Validate that tax lines appear only when their values are not '0.0', using the exact text from the code.
Execution:
  Arrange:
    - Valid customer; at least one item non-zero.
    - Set medical_tax='5.0', grocery_tax='0.0', cold_drinks_tax='12.5'.
  Act:
    - Call self.bill_area().
  Assert:
    - txtarea contains:
      - "\n Medical Tax\t\t\t5.0"
      - "\n Cold Drinks Tax\t\t\t12.5"
    - txtarea does not contain a "Grocery Tax" line.
Validation:
  Verifies conditional tax rendering and exact string outputs that customers see.

Scenario 11: Total line formatting uses self.total_bill and includes final separator
Details:
  TestName: test_bill_area_writes_total_and_trailing_separator
  Description: Ensure the total line is written with the current self.total_bill and the final separator is appended.
Execution:
  Arrange:
    - Valid customer; one or more items; taxes may be zero or non-zero.
    - Set self.total_bill -> 1234.56.
  Act:
    - Call self.bill_area().
  Assert:
    - txtarea contains a line exactly: "\n Total Bil:\t\t\t Rs.1234.56" (note: "Bil" as per code, without second 'l').
    - Followed by "\n--------------------------------".
Validation:
  Confirms that the bill ends with a total and a visual delimiter, aligning with the function’s structure.

Scenario 12: No further processing after validation errors (no save attempted)
Details:
  TestName: test_bill_area_does_not_save_on_validation_error
  Description: If a validation error occurs (missing customer details or no products), there should be no attempt to save the bill or open a dialog.
Execution:
  Arrange:
    - Case 1: c_name=" ", valid phone, non-zero prices.
    - Case 2: valid customer, all three price strings "Rs. 0.0".
    - Spy/monkeypatch self.save_bill and messagebox.askyesno.
  Act:
    - Call self.bill_area() in both cases.
  Assert:
    - self.save_bill is not called.
    - messagebox.askyesno is not called.
Validation:
  Prevents side effects and file prompts when the bill is invalid; reveals the missing early return after error paths.

Scenario 13: Save confirmation flow controls file creation
Details:
  TestName: test_bill_area_save_flow_yes_writes_file_no_does_not
  Description: Validate that save_bill respects the user’s confirmation and writes the bill content to "bills/<billno>.txt" only when confirmed.
Execution:
  Arrange:
    - Valid customer; at least one item to generate content.
    - Ensure tmp_path/"bills" directory exists.
    - Monkeypatch messagebox.askyesno to True for subcase A, False for subcase B.
    - Monkeypatch current working directory or ensure open writes into the tmp_path context.
  Act:
    - Call self.bill_area() for both subcases.
  Assert:
    - Subcase A (True): File "bills/<bill_no>.txt" exists; its content matches txtarea.get("1.0", END) at save time; messagebox.showinfo called with “Saved”.
    - Subcase B (False): File not created; messagebox.showinfo not called.
Validation:
  Confirms the persistence path and user consent behavior dictated by the provided save_bill dependency.

Scenario 14: Error path continues executing (current behavior) is caught
Details:
  TestName: test_bill_area_current_bug_continues_after_error
  Description: Document the current defect that after showing an error (e.g., no product purchased), the function continues to append lines and attempts to save.
Execution:
  Arrange:
    - Valid customer; all three price summaries "Rs. 0.0".
    - Set sanitizer=1 to make the continuation observable.
    - Monkeypatch save_bill to a spy that does nothing; capture txtarea insertions.
  Act:
    - Call self.bill_area().
  Assert:
    - messagebox.showerror called for "No Product Purchased".
    - Despite the error, txtarea contains item/tax/total lines and save_bill is called once.
    - Mark this as non-compliant with business rules; tests should fail once the function is fixed to return early.
Validation:
  Captures a critical control-flow defect so it can be fixed; once corrected, this scenario can be updated or flipped to assert correct early exit behavior.

"""

# ********RoostGPT********
import os
import random
import pytest
from types import MethodType
from tkinter import *
from tkinter import messagebox
from projects.Billing_system.biling_system import Bill_App

class Test_BillAppBillArea:

    @pytest.mark.invalid
    @pytest.mark.negative
    @pytest.mark.xfail(reason="bill_area continues after showing error for single-space customer details; missing early return")
    def test_bill_area_blocks_on_single_space_customer_fields(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v):
                self._v = v
            def get(self):
                return self._v
            def set(self, v):
                self._v = v

        class TextStub:
            def __init__(self):
                self.content = ""
            def delete(self, start, end):
                self.content = ""
            def insert(self, end_const, text):
                self.content += text
            def get(self, start, end):
                return self.content

        # Build minimal app object and bind methods from Bill_App
        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        # Variables
        app.c_name = Var(" ")
        app.c_phone = Var("valid-phone")
        app.medical_price = Var("Rs. 10.0")
        app.grocery_price = Var("Rs. 10.0")
        app.cold_drinks_price = Var("Rs. 10.0")

        # Item quantities (ensure at least one non-zero)
        app.sanitizer = Var(1)
        app.mask = Var(0)
        app.hand_gloves = Var(0)
        app.dettol = Var(0)
        app.newsprin = Var(0)
        app.thermal_gun = Var(0)

        app.rice = Var(0)
        app.food_oil = Var(0)
        app.wheat = Var(0)
        app.daal = Var(0)
        app.flour = Var(0)
        app.maggi = Var(0)

        app.sprite = Var(0)
        app.limka = Var(0)
        app.mazza = Var(0)
        app.coke = Var(0)
        app.fanta = Var(0)
        app.mountain_duo = Var(0)

        # Prices
        app.m_s_p = "Rs. 50"
        app.m_m_p = "Rs. 30"
        app.m_h_g_p = "Rs. 40"
        app.m_d_p = "Rs. 60"
        app.m_n_p = "Rs. 20"
        app.m_t_g_p = "Rs. 500"

        app.g_r_p = "Rs. 70"
        app.g_f_o_p = "Rs. 120"
        app.g_w_p = "Rs. 50"
        app.g_d_p = "Rs. 90"
        app.g_f_p = "Rs. 35"
        app.g_m_p = "Rs. 12"

        app.c_d_s_p = "Rs. 25"
        app.c_d_l_p = "Rs. 30"
        app.c_d_m_p = "Rs. 35"
        app.c_d_c_p = "Rs. 40"
        app.c_d_f_p = "Rs. 28"
        app.c_m_d = "Rs. 33"

        # Taxes and bill totals
        app.medical_tax = Var('0.0')
        app.grocery_tax = Var('0.0')
        app.cold_drinks_tax = Var('0.0')
        app.total_bill = 50.0
        app.bill_no = Var("1001")

        # Text area
        app.txtarea = TextStub()

        # Spy/stub messagebox and methods
        errors = []
        monkeypatch.setattr(messagebox, "showerror", lambda title, msg: errors.append((title, msg)))
        welcome_called = {"called": False}
        def welcome_spy():
            welcome_called["called"] = True
        app.welcome_bill = welcome_spy
        save_called = {"count": 0}
        def save_spy():
            save_called["count"] += 1
        app.save_bill = save_spy

        # Act
        app.bill_area()

        # Assert
        assert errors == [("Error", "Customer Details Are Must")]
        assert welcome_called["called"] is False
        assert app.txtarea.get("1.0", END) == ""
        assert save_called["count"] == 0

    @pytest.mark.invalid
    @pytest.mark.negative
    @pytest.mark.xfail(reason="bill_area does not block on empty strings for customer details; only checks single space")
    def test_bill_area_blocks_on_empty_customer_fields(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v):
                self._v = v
            def get(self):
                return self._v

        class TextStub:
            def __init__(self):
                self.content = ""
            def delete(self, start, end):
                self.content = ""
            def insert(self, end_const, text):
                self.content += text
            def get(self, start, end):
                return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("")
        app.c_phone = Var("")
        app.medical_price = Var("Rs. 15.0")
        app.grocery_price = Var("Rs. 5.0")
        app.cold_drinks_price = Var("Rs. 1.0")

        app.sanitizer = Var(1)
        app.mask = Var(0)
        app.hand_gloves = Var(0)
        app.dettol = Var(0)
        app.newsprin = Var(0)
        app.thermal_gun = Var(0)
        app.rice = Var(0)
        app.food_oil = Var(0)
        app.wheat = Var(0)
        app.daal = Var(0)
        app.flour = Var(0)
        app.maggi = Var(0)
        app.sprite = Var(0)
        app.limka = Var(0)
        app.mazza = Var(0)
        app.coke = Var(0)
        app.fanta = Var(0)
        app.mountain_duo = Var(0)

        app.m_s_p = "Rs. 50"
        app.m_m_p = "Rs. 30"
        app.m_h_g_p = "Rs. 40"
        app.m_d_p = "Rs. 60"
        app.m_n_p = "Rs. 20"
        app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"
        app.g_f_o_p = "Rs. 120"
        app.g_w_p = "Rs. 50"
        app.g_d_p = "Rs. 90"
        app.g_f_p = "Rs. 35"
        app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"
        app.c_d_l_p = "Rs. 30"
        app.c_d_m_p = "Rs. 35"
        app.c_d_c_p = "Rs. 40"
        app.c_d_f_p = "Rs. 28"
        app.c_m_d = "Rs. 33"

        app.medical_tax = Var('0.0')
        app.grocery_tax = Var('0.0')
        app.cold_drinks_tax = Var('0.0')
        app.total_bill = 50.0
        app.bill_no = Var("1002")

        app.txtarea = TextStub()

        errors = []
        monkeypatch.setattr(messagebox, "showerror", lambda t, m: errors.append((t, m)))
        save_called = {"count": 0}
        app.save_bill = lambda: save_called.__setitem__("count", save_called["count"] + 1)

        # Act
        app.bill_area()

        # Assert
        assert errors == [("Error", "Customer Details Are Must")]
        assert app.txtarea.get("1.0", END) == ""
        assert save_called["count"] == 0

    @pytest.mark.invalid
    @pytest.mark.negative
    @pytest.mark.xfail(reason="bill_area shows error on no product purchased but continues processing and calls save_bill; missing early return")
    def test_bill_area_blocks_on_all_zero_price_summaries(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v):
                self._v = v
            def get(self):
                return self._v
        class TextStub:
            def __init__(self):
                self.content = ""
            def delete(self, s, e):
                self.content = ""
            def insert(self, e, t):
                self.content += t
            def get(self, s, e):
                return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Alice")
        app.c_phone = Var("9876543210")
        app.medical_price = Var("Rs. 0.0")
        app.grocery_price = Var("Rs. 0.0")
        app.cold_drinks_price = Var("Rs. 0.0")

        # all quantities zero
        for attr in ["sanitizer","mask","hand_gloves","dettol","newsprin","thermal_gun",
                     "rice","food_oil","wheat","daal","flour","maggi",
                     "sprite","limka","mazza","coke","fanta","mountain_duo"]:
            setattr(app, attr, Var(0))

        # Prices
        app.m_s_p = "Rs. 50"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"

        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 0.0
        app.bill_no = Var("1003")
        app.txtarea = TextStub()

        errors = []
        monkeypatch.setattr(messagebox, "showerror", lambda t, m: errors.append((t, m)))
        save_calls = {"count": 0}
        app.save_bill = lambda: save_calls.__setitem__("count", save_calls["count"] + 1)
        # Act
        app.bill_area()

        # Assert
        assert errors == [("Error", "No Product Purchased")]
        assert app.txtarea.get("1.0", END) == ""
        assert save_calls["count"] == 0

    @pytest.mark.invalid
    @pytest.mark.negative
    @pytest.mark.xfail(reason="bill_area does not validate item quantities; it can generate a bill with no items when price summaries indicate non-zero")
    def test_bill_area_blocks_when_all_quantities_zero_regardless_of_price_strings(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v = v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content = ""
            def delete(self, s, e): self.content = ""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Bob")
        app.c_phone = Var("1234567890")
        app.medical_price = Var("Rs. 50.0")
        app.grocery_price = Var("Rs. 0.0")
        app.cold_drinks_price = Var("Rs. 0.0")

        # all quantities zero
        for attr in ["sanitizer","mask","hand_gloves","dettol","newsprin","thermal_gun",
                     "rice","food_oil","wheat","daal","flour","maggi",
                     "sprite","limka","mazza","coke","fanta","mountain_duo"]:
            setattr(app, attr, Var(0))

        # Prices and taxes
        app.m_s_p = "Rs. 50"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"
        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 50.0
        app.bill_no = Var("1004")
        app.txtarea = TextStub()

        errors = []
        monkeypatch.setattr(messagebox, "showerror", lambda t, m: errors.append((t, m)))
        save_calls = {"count": 0}
        app.save_bill = lambda: save_calls.__setitem__("count", save_calls["count"] + 1)

        # Act
        app.bill_area()

        # Assert
        assert errors == [("Error", "No Product Purchased")]
        assert "Products" not in app.txtarea.get("1.0", END)
        assert save_calls["count"] == 0

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_bill_area_calls_welcome_bill_and_writes_header(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v = v
            def get(self): return self._v
            def set(self, v): self._v = v
        class TextStub:
            def __init__(self): self.content = "junk to be cleared"
            def delete(self, s, e): self.content = ""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        # Use the provided welcome_bill behavior
        def bound_welcome(self):
            return Bill_App.welcome_bill(self)
        app.welcome_bill = MethodType(bound_welcome, app)

        app.c_name = Var("Carol")
        app.c_phone = Var("5555555555")
        app.medical_price = Var("Rs. 10.0")
        app.grocery_price = Var("Rs. 0.0")
        app.cold_drinks_price = Var("Rs. 0.0")

        app.sanitizer = Var(1)
        app.mask = Var(0)
        app.hand_gloves = Var(0)
        app.dettol = Var(0)
        app.newsprin = Var(0)
        app.thermal_gun = Var(0)
        app.rice = Var(0)
        app.food_oil = Var(0)
        app.wheat = Var(0)
        app.daal = Var(0)
        app.flour = Var(0)
        app.maggi = Var(0)
        app.sprite = Var(0)
        app.limka = Var(0)
        app.mazza = Var(0)
        app.coke = Var(0)
        app.fanta = Var(0)
        app.mountain_duo = Var(0)

        app.m_s_p = "Rs. 50"
        app.m_m_p = "Rs. 30"
        app.m_h_g_p = "Rs. 40"
        app.m_d_p = "Rs. 60"
        app.m_n_p = "Rs. 20"
        app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"
        app.g_f_o_p = "Rs. 120"
        app.g_w_p = "Rs. 50"
        app.g_d_p = "Rs. 90"
        app.g_f_p = "Rs. 35"
        app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"
        app.c_d_l_p = "Rs. 30"
        app.c_d_m_p = "Rs. 35"
        app.c_d_c_p = "Rs. 40"
        app.c_d_f_p = "Rs. 28"
        app.c_m_d = "Rs. 33"

        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 50.0
        app.bill_no = Var("2001")
        app.txtarea = TextStub()

        # Prevent actual save UI
        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        content = app.txtarea.get("1.0", END)
        assert content.startswith("\tWelcome Webcode Retail")
        assert f"\n Bill Number:{app.bill_no.get()}" in content
        assert f"\nCustomer Name:{app.c_name.get()}" in content
        assert f"\nPhone Number{app.c_phone.get()}" in content
        assert "\n================================" in content
        assert "\nProducts\t\tQTY\t\tPrice" in content
        # header precedes items
        assert content.index("Products") < content.index("Sanitizer")

    @pytest.mark.regression
    @pytest.mark.positive
    def test_bill_area_writes_sanitizer_line_correctly(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Dave")
        app.c_phone = Var("1111111111")
        app.medical_price = Var("Rs. 10.0")
        app.grocery_price = Var("Rs. 0.0")
        app.cold_drinks_price = Var("Rs. 0.0")

        app.sanitizer = Var(2)
        app.mask = Var(0); app.hand_gloves = Var(0); app.dettol = Var(0); app.newsprin = Var(0); app.thermal_gun = Var(0)
        app.rice = Var(0); app.food_oil = Var(0); app.wheat = Var(0); app.daal = Var(0); app.flour = Var(0); app.maggi = Var(0)
        app.sprite = Var(0); app.limka = Var(0); app.mazza = Var(0); app.coke = Var(0); app.fanta = Var(0); app.mountain_duo = Var(0)

        app.m_s_p = "Rs. 50"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"

        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 100
        app.bill_no = Var("2002")
        app.txtarea = TextStub()

        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        content = app.txtarea.get("1.0", END)
        assert "\n Sanitizer\t\t2\t\tRs. 50" in content
        # Ensure no other item lines accidentally printed
        assert "\n Mask\t\t" not in content
        assert "\n Hand Gloves\t\t" not in content

    @pytest.mark.regression
    @pytest.mark.invalid
    @pytest.mark.xfail(reason="bill_area mislabels and mis-maps several item lines (mask, limka, coke, fanta, thermal gun, mountain duo)")
    def test_bill_area_flags_label_and_quantity_price_mapping_inconsistencies(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Eve")
        app.c_phone = Var("2222222222")
        app.medical_price = Var("Rs. 100.0")
        app.grocery_price = Var("Rs. 0.0")
        app.cold_drinks_price = Var("Rs. 200.0")

        # Set quantities as specified
        app.sanitizer = Var(0)
        app.mask = Var(3)
        app.hand_gloves = Var(0)
        app.dettol = Var(0)
        app.newsprin = Var(0)
        app.thermal_gun = Var(1)

        app.rice = Var(0)
        app.food_oil = Var(0)
        app.wheat = Var(0)
        app.daal = Var(0)
        app.flour = Var(0)
        app.maggi = Var(0)

        app.sprite = Var(0)
        app.limka = Var(2)
        app.mazza = Var(0)
        app.coke = Var(4)
        app.fanta = Var(5)
        app.mountain_duo = Var(1)

        # Distinct prices for each
        app.m_s_p = "Rs. 51"; app.m_m_p = "Rs. 31"; app.m_h_g_p = "Rs. 41"; app.m_d_p = "Rs. 61"; app.m_n_p = "Rs. 21"; app.m_t_g_p = "Rs. 501"
        app.g_r_p = "Rs. 71"; app.g_f_o_p = "Rs. 121"; app.g_w_p = "Rs. 51"; app.g_d_p = "Rs. 91"; app.g_f_p = "Rs. 36"; app.g_m_p = "Rs. 13"
        app.c_d_s_p = "Rs. 26"; app.c_d_l_p = "Rs. 31"; app.c_d_m_p = "Rs. 36"; app.c_d_c_p = "Rs. 41"; app.c_d_f_p = "Rs. 29"; app.c_m_d = "Rs. 34"

        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 0.0
        app.bill_no = Var("2003")
        app.txtarea = TextStub()

        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert expected correct labels and quantities (business expectation)
        content = app.txtarea.get("1.0", END)
        assert f"\n Mask\t\t3\t\t{app.m_m_p}" in content
        assert f"\n Thermal Gun\t\t1\t\t{app.m_t_g_p}" in content
        assert f"\n Limka\t\t2\t\t{app.c_d_l_p}" in content
        assert f"\n Coke\t\t4\t\t{app.c_d_c_p}" in content
        assert f"\n Fanta\t\t5\t\t{app.c_d_f_p}" in content
        assert f"\n Mountain Duo\t\t1\t\t{app.c_m_d}" in content

    @pytest.mark.regression
    @pytest.mark.positive
    def test_bill_area_writes_grocery_lines_when_quantities_positive_only(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content
        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Grace"); app.c_phone = Var("9999999999")
        app.medical_price = Var("Rs. 0.0"); app.grocery_price = Var("Rs. 15.0"); app.cold_drinks_price = Var("Rs. 0.0")

        app.sanitizer = Var(0); app.mask = Var(0); app.hand_gloves = Var(0); app.dettol = Var(0); app.newsprin = Var(0); app.thermal_gun = Var(0)
        app.rice = Var(1); app.daal = Var(2); app.wheat = Var(0); app.flour = Var(0); app.food_oil = Var(0); app.maggi = Var(0)
        app.sprite = Var(0); app.limka = Var(0); app.mazza = Var(0); app.coke = Var(0); app.fanta = Var(0); app.mountain_duo = Var(0)

        app.m_s_p = "Rs. 50"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"

        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 230.0
        app.bill_no = Var("2004")
        app.txtarea = TextStub()

        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        content = app.txtarea.get("1.0", END)
        assert f"\n Rice\t\t1\t\t{app.g_r_p}" in content
        assert f"\n Daal\t\t2\t\t{app.g_d_p}" in content
        assert "\n Wheat\t\t" not in content
        assert "\n Flour\t\t" not in content
        assert "\n Food Oil\t\t" not in content
        assert "\n Maggi\t\t" not in content

    @pytest.mark.regression
    @pytest.mark.invalid
    @pytest.mark.parametrize("mountain_duo_qty,sprite_qty,expect_separator", [
        (0, 1, True),   # Expected consistent separator but current behavior lacks it
        (1, 0, True),   # Expected separator present
    ])
    @pytest.mark.xfail(reason="bill_area inserts a pre-tax separator only when mountain_duo is non-zero; inconsistent formatting")
    def test_bill_area_separator_before_taxes_is_consistent(self, mountain_duo_qty, sprite_qty, expect_separator, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Hank"); app.c_phone = Var("1010101010")
        app.medical_price = Var("Rs. 0.0"); app.grocery_price = Var("Rs. 0.0"); app.cold_drinks_price = Var("Rs. 10.0")

        # all other quantities zero
        for attr in ["sanitizer","mask","hand_gloves","dettol","newsprin","thermal_gun",
                     "rice","food_oil","wheat","daal","flour","maggi","limka","mazza","coke","fanta"]:
            setattr(app, attr, Var(0))
        app.sprite = Var(sprite_qty)
        app.mountain_duo = Var(mountain_duo_qty)

        app.m_s_p = "Rs. 50"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"
        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 25.0
        app.bill_no = Var("2005")
        app.txtarea = TextStub()

        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        content = app.txtarea.get("1.0", END)
        # Expect a separator before taxes regardless of mountain_duo quantity
        assert "\n--------------------------------" in content

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_bill_area_prints_tax_lines_conditionally(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content
        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Ivy"); app.c_phone = Var("2020202020")
        app.medical_price = Var("Rs. 5.0"); app.grocery_price = Var("Rs. 5.0"); app.cold_drinks_price = Var("Rs. 5.0")

        app.sanitizer = Var(1)
        for attr in ["mask","hand_gloves","dettol","newsprin","thermal_gun","rice","food_oil","wheat","daal","flour","maggi","sprite","limka","mazza","coke","fanta","mountain_duo"]:
            setattr(app, attr, Var(0))

        app.m_s_p = "Rs. 10"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"

        app.medical_tax = Var('5.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('12.5')
        app.total_bill = 100.0
        app.bill_no = Var("2006")
        app.txtarea = TextStub()

        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        content = app.txtarea.get("1.0", END)
        assert "\n Medical Tax\t\t\t5.0" in content
        assert "\n Cold Drinks Tax\t\t\t12.5" in content
        assert "\n Grocery Tax\t\t\t" not in content

    @pytest.mark.smoke
    @pytest.mark.positive
    def test_bill_area_writes_total_and_trailing_separator(self, monkeypatch):
        # Arrange
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content
        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        app.save_bill = MethodType(Bill_App.save_bill, app)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("John"); app.c_phone = Var("3030303030")
        app.medical_price = Var("Rs. 10.0"); app.grocery_price = Var("Rs. 0.0"); app.cold_drinks_price = Var("Rs. 0.0")

        app.sanitizer = Var(1)
        for attr in ["mask","hand_gloves","dettol","newsprin","thermal_gun","rice","food_oil","wheat","daal","flour","maggi","sprite","limka","mazza","coke","fanta","mountain_duo"]:
            setattr(app, attr, Var(0))

        app.m_s_p = "Rs. 10"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"

        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 1234.56  # TODO: Adjust expected total based on calculation logic if needed
        app.bill_no = Var("2007")
        app.txtarea = TextStub()

        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        content = app.txtarea.get("1.0", END)
        assert "\n Total Bil:\t\t\t Rs.1234.56" in content
        assert content.strip().endswith("--------------------------------")

    @pytest.mark.security
    @pytest.mark.invalid
    @pytest.mark.xfail(reason="bill_area proceeds after validation errors and still calls save_bill; should abort without side effects")
    def test_bill_area_does_not_save_on_validation_error(self, monkeypatch):
        # Case 1: customer name single space
        def build_app_for_case1():
            class Var:
                def __init__(self, v): self._v=v
                def get(self): return self._v
            class TextStub:
                def __init__(self): self.content=""
                def delete(self, s, e): self.content=""
                def insert(self, e, t): self.content += t
                def get(self, s, e): return self.content
            app = type("FakeApp", (), {})()
            app.bill_area = MethodType(Bill_App.bill_area, app)
            app.save_bill = MethodType(Bill_App.save_bill, app)
            app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

            app.c_name = Var(" "); app.c_phone = Var("1111111111")
            app.medical_price = Var("Rs. 10.0"); app.grocery_price = Var("Rs. 10.0"); app.cold_drinks_price = Var("Rs. 10.0")
            app.sanitizer = Var(1)
            for attr in ["mask","hand_gloves","dettol","newsprin","thermal_gun","rice","food_oil","wheat","daal","flour","maggi","sprite","limka","mazza","coke","fanta","mountain_duo"]:
                setattr(app, attr, Var(0))
            app.m_s_p="Rs.50"; app.m_m_p="Rs.30"; app.m_h_g_p="Rs.40"; app.m_d_p="Rs.60"; app.m_n_p="Rs.20"; app.m_t_g_p="Rs.500"
            app.g_r_p="Rs.70"; app.g_f_o_p="Rs.120"; app.g_w_p="Rs.50"; app.g_d_p="Rs.90"; app.g_f_p="Rs.35"; app.g_m_p="Rs.12"
            app.c_d_s_p="Rs.25"; app.c_d_l_p="Rs.30"; app.c_d_m_p="Rs.35"; app.c_d_c_p="Rs.40"; app.c_d_f_p="Rs.28"; app.c_m_d="Rs.33"
            app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
            app.total_bill = 50.0; app.bill_no = Var("3001")
            app.txtarea = TextStub()
            return app

        app1 = build_app_for_case1()
        errors1 = []
        ask_calls1 = {"count": 0}
        save_calls1 = {"count": 0}
        monkeypatch.setattr(messagebox, "showerror", lambda t, m: errors1.append((t, m)))
        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: ask_calls1.__setitem__("count", ask_calls1["count"] + 1) or False)
        app1.save_bill = lambda: save_calls1.__setitem__("count", save_calls1["count"] + 1)

        app1.bill_area()
        assert errors1, "Expected an error message for missing customer details"
        assert ask_calls1["count"] == 0
        assert save_calls1["count"] == 0

        # Case 2: all three price strings zero
        class Var2:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub2:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app2 = type("FakeApp", (), {})()
        app2.bill_area = MethodType(Bill_App.bill_area, app2)
        app2.save_bill = MethodType(Bill_App.save_bill, app2)
        app2.welcome_bill = MethodType(Bill_App.welcome_bill, app2)
        app2.c_name = Var2("Zoe"); app2.c_phone = Var2("7777777777")
        app2.medical_price = Var2("Rs. 0.0"); app2.grocery_price = Var2("Rs. 0.0"); app2.cold_drinks_price = Var2("Rs. 0.0")
        for attr in ["sanitizer","mask","hand_gloves","dettol","newsprin","thermal_gun","rice","food_oil","wheat","daal","flour","maggi","sprite","limka","mazza","coke","fanta","mountain_duo"]:
            setattr(app2, attr, Var2(0))
        app2.m_s_p="Rs.50"; app2.m_m_p="Rs.30"; app2.m_h_g_p="Rs.40"; app2.m_d_p="Rs.60"; app2.m_n_p="Rs.20"; app2.m_t_g_p="Rs.500"
        app2.g_r_p="Rs.70"; app2.g_f_o_p="Rs.120"; app2.g_w_p="Rs.50"; app2.g_d_p="Rs.90"; app2.g_f_p="Rs.35"; app2.g_m_p="Rs.12"
        app2.c_d_s_p="Rs.25"; app2.c_d_l_p="Rs.30"; app2.c_d_m_p="Rs.35"; app2.c_d_c_p="Rs.40"; app2.c_d_f_p="Rs.28"; app2.c_m_d="Rs.33"
        app2.medical_tax = Var2('0.0'); app2.grocery_tax = Var2('0.0'); app2.cold_drinks_tax = Var2('0.0')
        app2.total_bill = 0.0; app2.bill_no = Var2("3002")
        app2.txtarea = TextStub2()
        errors2 = []
        ask_calls2 = {"count": 0}
        save_calls2 = {"count": 0}
        monkeypatch.setattr(messagebox, "showerror", lambda t, m: errors2.append((t, m)))
        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: ask_calls2.__setitem__("count", ask_calls2["count"] + 1) or False)
        app2.save_bill = lambda: save_calls2.__setitem__("count", save_calls2["count"] + 1)

        app2.bill_area()
        assert errors2 == [("Error", "No Product Purchased")]
        assert ask_calls2["count"] == 0
        assert save_calls2["count"] == 0

    @pytest.mark.regression
    @pytest.mark.positive
    def test_bill_area_save_flow_yes_writes_file_no_does_not(self, monkeypatch, tmp_path):
        # Arrange shared builder
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        def build_app():
            app = type("FakeApp", (), {})()
            app.bill_area = MethodType(Bill_App.bill_area, app)
            app.save_bill = MethodType(Bill_App.save_bill, app)
            app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

            app.c_name = Var("Yara"); app.c_phone = Var("6060606060")
            app.medical_price = Var("Rs. 10.0"); app.grocery_price = Var("Rs. 0.0"); app.cold_drinks_price = Var("Rs. 0.0")
            app.sanitizer = Var(1)
            for attr in ["mask","hand_gloves","dettol","newsprin","thermal_gun","rice","food_oil","wheat","daal","flour","maggi","sprite","limka","mazza","coke","fanta","mountain_duo"]:
                setattr(app, attr, Var(0))
            app.m_s_p = "Rs. 10"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
            app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
            app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"
            app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
            app.total_bill = 10.0
            # Use deterministic bill number
            app.bill_no = Var("5001")  # TODO: change bill number if needed for isolation
            app.txtarea = TextStub()
            return app

        bills_dir = tmp_path / "bills"
        bills_dir.mkdir()

        # Subcase A: askyesno returns True
        app_yes = build_app()
        monkeypatch.chdir(tmp_path)
        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: True)
        saved = []
        monkeypatch.setattr(messagebox, "showinfo", lambda t, m: saved.append((t, m)))

        app_yes.bill_area()
        expected_path = bills_dir / f"{app_yes.bill_no.get()}.txt"
        assert expected_path.exists()
        with expected_path.open("r") as f:
            file_content = f.read()
        assert file_content == app_yes.txtarea.get("1.0", END)
        assert saved and saved[0][0] == "Saved"

        # Subcase B: askyesno returns False
        app_no = build_app()
        # Change bill number to avoid collisions
        app_no.bill_no = Var("5002")  # TODO: adjust if unique numbering is needed
        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)
        infos = []
        monkeypatch.setattr(messagebox, "showinfo", lambda t, m: infos.append((t, m)))

        app_no.bill_area()
        expected_path_b = bills_dir / f"{app_no.bill_no.get()}.txt"
        assert not expected_path_b.exists()
        assert infos == []

    @pytest.mark.regression
    @pytest.mark.invalid
    def test_bill_area_current_bug_continues_after_error(self, monkeypatch):
        # Arrange to demonstrate current defect: all prices zero (No Product Purchased) but it continues
        class Var:
            def __init__(self, v): self._v=v
            def get(self): return self._v
        class TextStub:
            def __init__(self): self.content=""
            def delete(self, s, e): self.content=""
            def insert(self, e, t): self.content += t
            def get(self, s, e): return self.content

        app = type("FakeApp", (), {})()
        app.bill_area = MethodType(Bill_App.bill_area, app)
        # Spy on save_bill
        save_calls = {"count": 0}
        app.save_bill = lambda: save_calls.__setitem__("count", save_calls["count"] + 1)
        app.welcome_bill = MethodType(Bill_App.welcome_bill, app)

        app.c_name = Var("Liam"); app.c_phone = Var("9090909090")
        app.medical_price = Var("Rs. 0.0"); app.grocery_price = Var("Rs. 0.0"); app.cold_drinks_price = Var("Rs. 0.0")

        # Make sanitizer non-zero to observe continuation
        app.sanitizer = Var(1)
        for attr in ["mask","hand_gloves","dettol","newsprin","thermal_gun","rice","food_oil","wheat","daal","flour","maggi","sprite","limka","mazza","coke","fanta","mountain_duo"]:
            setattr(app, attr, Var(0))

        app.m_s_p = "Rs. 10"; app.m_m_p = "Rs. 30"; app.m_h_g_p = "Rs. 40"; app.m_d_p = "Rs. 60"; app.m_n_p = "Rs. 20"; app.m_t_g_p = "Rs. 500"
        app.g_r_p = "Rs. 70"; app.g_f_o_p = "Rs. 120"; app.g_w_p = "Rs. 50"; app.g_d_p = "Rs. 90"; app.g_f_p = "Rs. 35"; app.g_m_p = "Rs. 12"
        app.c_d_s_p = "Rs. 25"; app.c_d_l_p = "Rs. 30"; app.c_d_m_p = "Rs. 35"; app.c_d_c_p = "Rs. 40"; app.c_d_f_p = "Rs. 28"; app.c_m_d = "Rs. 33"
        app.medical_tax = Var('0.0'); app.grocery_tax = Var('0.0'); app.cold_drinks_tax = Var('0.0')
        app.total_bill = 10.0
        app.bill_no = Var("6001")
        app.txtarea = TextStub()

        errors = []
        monkeypatch.setattr(messagebox, "showerror", lambda t, m: errors.append((t, m)))
        monkeypatch.setattr(messagebox, "askyesno", lambda *a, **k: False)  # prevent file write dialogs
        monkeypatch.setattr(messagebox, "showinfo", lambda *a, **k: None)

        # Act
        app.bill_area()

        # Assert
        assert ("Error", "No Product Purchased") in errors
        content = app.txtarea.get("1.0", END)
        assert "Sanitizer" in content or "Products" in content, "Expected item or structure to be appended despite error"
        assert save_calls["count"] == 1, "save_bill was expected to be called due to the current defect"