# ********RoostGPT********
"""
Test generated by RoostGPT for test demo-python using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=Bill_App.save_bill_420ec392d0
ROOST_METHOD_SIG_HASH=Bill_App.save_bill_4312133209


Scenario 1: Successful save when the user confirms
Details:
  TestName: test_save_bill_confirms_writes_file_and_shows_success_message
  Description: Verifies the happy path where the user confirms saving; the function reads the text area, writes content to the correct file under the bills directory, stores bill_data, and shows a success message.
Execution:
  Arrange:
    - Prepare a fake self with:
      - self.txtarea.get returning "Item A x2\nTotal: $10\n"
      - self.bill_no.get returning "12345"
    - Ensure a temporary working directory with a pre-existing "bills" subfolder.
    - Patch messagebox.askyesno to return True.
    - Spy on messagebox.showinfo.
  Act:
    - Invoke save_bill(self).
  Assert:
    - messagebox.askyesno called once with ("Save Bill", "Do you want to save the bill?")
    - self.txtarea.get called once with ('1.0', END)
    - File bills/12345.txt created and contains exactly "Item A x2\nTotal: $10\n"
    - self.bill_data equals "Item A x2\nTotal: $10\n"
    - messagebox.showinfo called once with ("Saved", "Bill no:12345 Saved Successfully")
Validation:
  This scenario validates the core business requirement: upon user confirmation, the bill is persisted and the user is notified. It also ensures the function reads the correct range from the text area and uses bill_no as the file name.

"""

# ********RoostGPT********
import os
import random
from unittest.mock import MagicMock
import pytest
from tkinter import *
from tkinter import messagebox

class Test_BillAppSaveBill:

    @pytest.mark.smoke
    @pytest.mark.regression
    @pytest.mark.positive
    def test_save_bill_confirms_writes_file_and_shows_success_message(self, tmp_path, monkeypatch):
        # Arrange
        # Ensure temporary working directory and pre-existing "bills" subfolder
        monkeypatch.chdir(tmp_path)
        os.makedirs("bills", exist_ok=True)

        bill_text = "Item A x2\nTotal: $10\n"
        bill_no_value = "12345"  # TODO: Change this value if you want to test with a different bill number

        # Patch messagebox methods
        askyesno_mock = MagicMock(return_value=True)
        showinfo_mock = MagicMock()
        monkeypatch.setattr(messagebox, "askyesno", askyesno_mock)
        monkeypatch.setattr(messagebox, "showinfo", showinfo_mock)

        # Prepare a fake self object with required attributes and behaviors
        fake_self = type("FakeSelf", (), {})()
        fake_self.txtarea = MagicMock()
        fake_self.txtarea.get = MagicMock(return_value=bill_text)
        fake_self.bill_no = MagicMock()
        fake_self.bill_no.get = MagicMock(return_value=bill_no_value)

        # Import the class and invoke the method under test
        from projects.Billing_system.biling_system import Bill_App
        Bill_App.save_bill(fake_self)

        # Assert
        askyesno_mock.assert_called_once_with("Save Bill", "Do you want to save the bill?")
        fake_self.txtarea.get.assert_called_once_with('1.0', END)

        expected_file_path = os.path.join("bills", f"{bill_no_value}.txt")
        assert os.path.isfile(expected_file_path), f"Expected file was not created at: {expected_file_path}"

        with open(expected_file_path, "r") as f:
            saved_content = f.read()
        assert saved_content == bill_text

        assert getattr(fake_self, "bill_data", None) == bill_text
        showinfo_mock.assert_called_once_with("Saved", f"Bill no:{bill_no_value} Saved Successfully")