# ********RoostGPT********
"""
Test generated by RoostGPT for test demo-python using AI Type Azure Open AI and AI Model gpt-5

ROOST_METHOD_HASH=Bill_App.clear_data_039b9b5ff8
ROOST_METHOD_SIG_HASH=Bill_App.clear_data_75709990c7


 
Scenario 1: Confirmed clear resets all numeric counters to zero
Details:
  TestName: test_clear_data_confirms_resets_intvars_to_zero
  Description: Verifies that when the user confirms, all product-related IntVar counters are reset to 0 across medical, grocery, and cold drinks categories.
Execution:
  Arrange: 
    - Initialize a Tk root (withdraw).
    - Instantiate Bill_App(root).
    - Set all relevant IntVar attributes to non-zero values (e.g., sanitizer=3, rice=5, sprite=2, etc.).
    - monkeypatch tkinter.messagebox.askyesno to return True.
    - monkeypatch self.welcome_bill to a no-op spy to avoid GUI coupling.
  Act:
    - Call obj.clear_data().
  Assert:
    - For each IntVar: .get() == 0 (sanitizer, mask, hand_gloves, dettol, newsprin, thermal_gun, rice, food_oil, wheat, daal, flour, maggi, sprite, limka, mazza, coke, fanta, mountain_duo).
    - Spy confirms welcome_bill was called once.
Validation:
  This test confirms the core clearing behavior for all quantity counters, matching the business requirement to revert counts to a clean slate on user confirmation.

"""

# ********RoostGPT********
import pytest
from tkinter import *
import random
import os
from tkinter import messagebox
from projects.Billing_system.biling_system import Bill_App
import importlib

class Test_BillAppClearData:
    @pytest.mark.smoke
    @pytest.mark.regression
    @pytest.mark.positive
    def test_clear_data_confirms_resets_intvars_to_zero(self, monkeypatch):
        # Arrange
        # Initialize Tk root and app instance
        root = Tk()
        root.withdraw()
        try:
            app = Bill_App(root)

            # Set all relevant IntVar attributes to non-zero values
            # TODO: Adjust non-zero values if product ranges change in future
            initial_values = {
                "sanitizer": 3,
                "mask": 4,
                "hand_gloves": 7,
                "dettol": 2,
                "newsprin": 6,
                "thermal_gun": 1,
                "rice": 5,
                "food_oil": 9,
                "wheat": 8,
                "daal": 3,
                "flour": 4,
                "maggi": 10,
                "sprite": 2,
                "limka": 11,
                "mazza": 12,
                "coke": 13,
                "fanta": 14,
                "mountain_duo": 15,
            }

            for attr_name, value in initial_values.items():
                getattr(app, attr_name).set(value)

            # Patch messagebox.askyesno in the module where Bill_App is defined to always confirm
            billing_module = importlib.import_module("projects.Billing_system.biling_system")
            monkeypatch.setattr(billing_module.messagebox, "askyesno", lambda *args, **kwargs: True)

            # Monkeypatch welcome_bill to a no-op spy to avoid GUI coupling
            call_counter = {"count": 0}

            def welcome_bill_spy():
                call_counter["count"] += 1

            monkeypatch.setattr(app, "welcome_bill", welcome_bill_spy)

            # Act
            app.clear_data()

            # Assert: all IntVars are reset to zero
            for attr_name in initial_values.keys():
                assert getattr(app, attr_name).get() == 0, f"{attr_name} was not reset to 0"

            # Assert: welcome_bill was called exactly once
            assert call_counter["count"] == 1, "welcome_bill should be called once after clearing data"
        finally:
            try:
                root.destroy()
            except Exception:
                pass