# ********RoostGPT********

# Test generated by RoostGPT for test API-test-file using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /timezone.json_get for http method type GET 
# RoostTestHash=df6b1e5ce9
# 
# 

# ********RoostGPT********
"""
Test Suite for Time Zone API Endpoint

This module contains comprehensive pytest tests for the /v1/timezone.json endpoint.
Tests cover successful responses, error scenarios, and schema validation.

Setup:
    1. Ensure config.yml is properly configured with API host and authentication
    2. Set environment variables: API_HOST, key (for ApiKeyAuth)
    3. Place timezone_json.json in the same directory as this test file
    4. Install dependencies: pytest, requests, pyyaml, jsonschema

Execution:
    pytest test_timezone.py -v
    pytest test_timezone.py -v -m smoke  # Run only smoke tests
"""

import json
import os
import pytest
from pathlib import Path

# Import validator from validator.py
from validator import SwaggerSchemaValidator

# Constants
ENDPOINT = "/v1/timezone.json"
API_SPEC_PATH = "api.json"

# Load test data from JSON file
TEST_DATA_FILE = Path(__file__).parent / "timezone_json.json"


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load endpoint-specific test data from JSON file."""
    with open(TEST_DATA_FILE, "r") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize the SwaggerSchemaValidator with API spec."""
    return SwaggerSchemaValidator(API_SPEC_PATH)


@pytest.fixture(scope="function")
def test_params(config_test_data, endpoint_test_data, request):
    """
    Merge config_test_data with endpoint_test_data for each test scenario.
    Override default config values with scenario-specific values.
    """
    # Get scenario index from test parameter if available
    scenario_index = getattr(request, "param", 0)
    scenario_data = endpoint_test_data[scenario_index] if scenario_index < len(endpoint_test_data) else {}
    
    # Merge config_test_data with scenario_data (scenario takes precedence)
    merged = {**config_test_data, **scenario_data}
    return merged


class TestTimezoneAPISuccess:
    """Test class for successful Time Zone API responses."""

    @pytest.mark.smoke
    @pytest.mark.parametrize("scenario_index", range(2))  # Based on JSON file having 2 entries
    def test_timezone_success_scenarios(
        self, api_client, schema_validator, endpoint_test_data, config_test_data, scenario_index
    ):
        """
        Test successful timezone API responses using table-driven data.
        
        This test iterates through all scenarios defined in timezone_json.json
        and validates:
        - Response status code matches expected
        - Response schema matches OpenAPI specification
        """
        # Get scenario data from JSON file
        scenario = endpoint_test_data[scenario_index]
        
        # Merge with config_test_data (scenario overrides defaults)
        test_data = {**config_test_data, **scenario}
        
        # Extract required parameter from test data
        query_param = test_data.get("q")
        expected_status = test_data.get("statusCode")
        scenario_name = test_data.get("scenario", "Unknown scenario")
        
        # Make API request with required parameter
        params = {"q": query_param}
        response = api_client.get(ENDPOINT, params=params)
        
        # Assert status code
        assert response.status_code == expected_status, (
            f"Scenario: {scenario_name} - "
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema for successful responses
        if expected_status == 200:
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, "GET", str(expected_status), response
            )
            assert validation_result["valid"], (
                f"Schema validation failed for scenario '{scenario_name}': "
                f"{validation_result.get('message', 'Unknown error')}"
            )
            
            # Verify response contains expected fields
            response_json = response.json()
            expected_fields = ["name", "region", "country", "lat", "lon", "tz_id", "localtime_epoch", "localtime"]
            for field in expected_fields:
                assert field in response_json, f"Missing expected field '{field}' in response"


class TestTimezoneAPIErrors:
    """Test class for Time Zone API error responses."""

    def test_missing_required_parameter_q(self, api_client, schema_validator):
        """
        Test API response when required parameter 'q' is not provided.
        
        Expected: 400 Bad Request with error code 1003
        """
        # Make request without required 'q' parameter
        response = api_client.get(ENDPOINT, params={})
        
        # API returns 400 for missing required parameter
        assert response.status_code == 400, (
            f"Expected status 400 for missing 'q' parameter, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )
        
        # Verify error response structure
        response_json = response.json()
        assert "error" in response_json or "code" in response_json or "message" in response_json, (
            "Error response should contain error details"
        )

    def test_invalid_location_parameter(self, api_client, schema_validator):
        """
        Test API response when 'q' parameter contains invalid/non-existent location.
        
        Expected: 400 Bad Request with error code 1006 (No location found)
        """
        # Use a clearly invalid location string
        params = {"q": "xyznonexistentlocation12345"}
        response = api_client.get(ENDPOINT, params=params)
        
        # API returns 400 for invalid location
        assert response.status_code == 400, (
            f"Expected status 400 for invalid location, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_empty_q_parameter(self, api_client, schema_validator):
        """
        Test API response when 'q' parameter is empty string.
        
        Expected: 400 Bad Request
        """
        params = {"q": ""}
        response = api_client.get(ENDPOINT, params=params)
        
        # Empty parameter should result in 400 error
        assert response.status_code == 400, (
            f"Expected status 400 for empty 'q' parameter, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )


class TestTimezoneAPIAuthentication:
    """Test class for authentication-related error responses."""

    def test_missing_api_key(self, api_host, schema_validator):
        """
        Test API response when API key is not provided.
        
        Expected: 401 Unauthorized with error code 1002
        """
        import requests
        
        # Make request without API key
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        params = {"q": "London"}
        response = requests.get(url, params=params, timeout=30)
        
        # API returns 401 for missing API key
        assert response.status_code == 401, (
            f"Expected status 401 for missing API key, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "401", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_invalid_api_key(self, api_host, schema_validator):
        """
        Test API response when invalid API key is provided.
        
        Expected: 401 Unauthorized with error code 2006
        """
        import requests
        
        # Make request with invalid API key
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        params = {"q": "London", "key": "invalid_api_key_12345"}
        response = requests.get(url, params=params, timeout=30)
        
        # API returns 401 for invalid API key
        assert response.status_code == 401, (
            f"Expected status 401 for invalid API key, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "401", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )


class TestTimezoneAPIBoundaryConditions:
    """Test class for boundary conditions and edge cases."""

    @pytest.mark.parametrize("location_type,location_value", [
        ("zipcode", "10001"),  # US Zipcode
        ("postcode", "SW1A 1AA"),  # UK Postcode
        ("coordinates", "40.71,-74.01"),  # Latitude/Longitude
        ("ip_address", "8.8.8.8"),  # IP address
    ])
    def test_various_location_formats(
        self, api_client, schema_validator, location_type, location_value
    ):
        """
        Test API with various supported location formats.
        
        The API supports: US Zipcode, UK Postcode, Canada Postalcode,
        IP address, Latitude/Longitude, and city name.
        """
        params = {"q": location_value}
        response = api_client.get(ENDPOINT, params=params)
        
        # These should return either 200 (success) or 400 (location not found)
        # depending on the validity of the location
        assert response.status_code in [200, 400], (
            f"Unexpected status {response.status_code} for {location_type}: {location_value}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema based on status code
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", str(response.status_code), response
        )
        assert validation_result["valid"], (
            f"Schema validation failed for {location_type}: "
            f"{validation_result.get('message', 'Unknown error')}"
        )

    def test_special_characters_in_query(self, api_client, schema_validator):
        """
        Test API behavior with special characters in query parameter.
        
        Expected: 400 Bad Request (invalid location)
        """
        params = {"q": "!@#$%^&*()"}
        response = api_client.get(ENDPOINT, params=params)
        
        # Special characters should result in 400 error
        assert response.status_code == 400, (
            f"Expected status 400 for special characters, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_very_long_query_parameter(self, api_client, schema_validator):
        """
        Test API behavior with excessively long query parameter.
        
        Expected: 400 Bad Request
        """
        # Create a very long string
        long_query = "a" * 1000
        params = {"q": long_query}
        response = api_client.get(ENDPOINT, params=params)
        
        # Long query should result in 400 error
        assert response.status_code == 400, (
            f"Expected status 400 for very long query, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )


class TestTimezoneAPIResponseValidation:
    """Test class for detailed response validation."""

    @pytest.mark.smoke
    def test_response_data_types(self, api_client, endpoint_test_data, config_test_data):
        """
        Test that response fields have correct data types as per API spec.
        """
        # Use first scenario from test data
        scenario = endpoint_test_data[0]
        test_data = {**config_test_data, **scenario}
        
        params = {"q": test_data.get("q")}
        response = api_client.get(ENDPOINT, params=params)
        
        if response.status_code == 200:
            response_json = response.json()
            
            # Validate data types according to API spec
            if "name" in response_json:
                assert isinstance(response_json["name"], str), "name should be string"
            if "region" in response_json:
                assert isinstance(response_json["region"], str), "region should be string"
            if "country" in response_json:
                assert isinstance(response_json["country"], str), "country should be string"
            if "lat" in response_json:
                assert isinstance(response_json["lat"], (int, float)), "lat should be number"
            if "lon" in response_json:
                assert isinstance(response_json["lon"], (int, float)), "lon should be number"
            if "tz_id" in response_json:
                assert isinstance(response_json["tz_id"], str), "tz_id should be string"
            if "localtime_epoch" in response_json:
                assert isinstance(response_json["localtime_epoch"], int), "localtime_epoch should be integer"
            if "localtime" in response_json:
                assert isinstance(response_json["localtime"], str), "localtime should be string"

    @pytest.mark.smoke
    def test_response_contains_location_data(self, api_client, endpoint_test_data, config_test_data):
        """
        Test that successful response contains meaningful location data.
        """
        # Use first scenario from test data
        scenario = endpoint_test_data[0]
        test_data = {**config_test_data, **scenario}
        
        params = {"q": test_data.get("q")}
        response = api_client.get(ENDPOINT, params=params)
        
        if response.status_code == 200:
            response_json = response.json()
            
            # Verify location coordinates are within valid ranges
            if "lat" in response_json:
                assert -90 <= response_json["lat"] <= 90, "Latitude should be between -90 and 90"
            if "lon" in response_json:
                assert -180 <= response_json["lon"] <= 180, "Longitude should be between -180 and 180"
            
            # Verify timezone ID is not empty
            if "tz_id" in response_json:
                assert len(response_json["tz_id"]) > 0, "tz_id should not be empty"
