# ********RoostGPT********

# Test generated by RoostGPT for test API-test-file using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /history.json_get for http method type GET 
# RoostTestHash=6ba88fbe10
# 
# 

# ********RoostGPT********
"""
Test Suite for Weather API History Endpoint

This module contains comprehensive pytest tests for the /v1/history.json endpoint.
The tests cover various scenarios including successful responses, error handling,
and schema validation.

Setup:
    1. Ensure config.yml is properly configured with API host and authentication
    2. Set environment variables: API_HOST, key (for ApiKeyAuth)
    3. Place history_json.json in the same directory as this test file
    4. Install dependencies: pytest, requests, pyyaml, jsonschema

Execution:
    pytest test_history.py -v
    pytest test_history.py -v -m smoke  # Run only smoke tests
"""

import json
import os
import pytest
from pathlib import Path

# Import validator from validator.py
from validator import SwaggerSchemaValidator


# Constants
ENDPOINT = "/v1/history.json"
API_SPEC_PATH = "api.json"


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load test data from history_json.json file."""
    test_data_path = Path(__file__).parent / "history_json.json"
    with open(test_data_path, "r") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize the SwaggerSchemaValidator with the API spec."""
    spec_path = Path(__file__).parent / API_SPEC_PATH
    return SwaggerSchemaValidator(str(spec_path))


class TestHistoryAPISuccess:
    """Test class for successful History API responses."""

    @pytest.mark.smoke
    def test_history_with_required_params_only(self, api_client, config_test_data, endpoint_test_data, schema_validator):
        """
        Test History API with only required parameters (q and dt).
        This is a smoke test covering the happy path with minimal required data.
        """
        # Use first test case from endpoint_test_data for required params
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        expected_status = test_case.get("statusCode", 200)
        assert response.status_code == expected_status, (
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", str(expected_status), response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    @pytest.mark.smoke
    @pytest.mark.parametrize("test_case_index", range(2))
    def test_history_table_driven(self, api_client, endpoint_test_data, schema_validator, test_case_index):
        """
        Table-driven test for History API using data from history_json.json.
        Iterates through all test cases in the JSON file.
        """
        if test_case_index >= len(endpoint_test_data):
            pytest.skip(f"Test case index {test_case_index} out of range")
        
        test_case = endpoint_test_data[test_case_index]
        
        # Build params from test case - only include keys that exist
        params = {}
        
        # Required parameters
        if "q" in test_case:
            params["q"] = test_case["q"]
        if "dt" in test_case:
            params["dt"] = test_case["dt"]
        
        # Optional parameters
        if "unixdt" in test_case:
            params["unixdt"] = test_case["unixdt"]
        if "end_dt" in test_case:
            params["end_dt"] = test_case["end_dt"]
        if "unixend_dt" in test_case:
            params["unixend_dt"] = test_case["unixend_dt"]
        if "hour" in test_case:
            params["hour"] = test_case["hour"]
        if "lang" in test_case:
            params["lang"] = test_case["lang"]
        
        response = api_client.get(ENDPOINT, params=params)
        
        expected_status = test_case.get("statusCode", 200)
        assert response.status_code == expected_status, (
            f"Scenario: {test_case.get('scenario', 'Unknown')}. "
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema for successful responses
        if expected_status == 200:
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, "GET", str(expected_status), response
            )
            assert validation_result["valid"], (
                f"Schema validation failed for scenario '{test_case.get('scenario')}': "
                f"{validation_result.get('message', 'Unknown error')}"
            )
            
            # Validate response contains expected structure
            response_json = response.json()
            assert "location" in response_json, "Response should contain 'location' object"
            assert "forecast" in response_json, "Response should contain 'forecast' object"

    def test_history_with_all_optional_params(self, api_client, endpoint_test_data, schema_validator):
        """
        Test History API with all optional parameters included.
        Uses test case that has optional parameters defined.
        """
        # Find test case with optional parameters
        test_case = None
        for tc in endpoint_test_data:
            if "end_dt" in tc or "hour" in tc or "lang" in tc:
                test_case = tc
                break
        
        if test_case is None:
            pytest.skip("No test case with optional parameters found")
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        # Add optional parameters if present
        if "unixdt" in test_case:
            params["unixdt"] = test_case["unixdt"]
        if "end_dt" in test_case:
            params["end_dt"] = test_case["end_dt"]
        if "unixend_dt" in test_case:
            params["unixend_dt"] = test_case["unixend_dt"]
        if "hour" in test_case:
            params["hour"] = test_case["hour"]
        if "lang" in test_case:
            params["lang"] = test_case["lang"]
        
        response = api_client.get(ENDPOINT, params=params)
        
        expected_status = test_case.get("statusCode", 200)
        assert response.status_code == expected_status, (
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", str(expected_status), response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )


class TestHistoryAPIValidation:
    """Test class for History API validation and error scenarios."""

    def test_missing_required_param_q(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that missing required parameter 'q' returns 400 error.
        Error code 1003: Parameter 'q' not provided.
        """
        test_case = endpoint_test_data[0]
        
        # Only provide 'dt', missing 'q'
        params = {
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API spec indicates 400 for missing 'q' parameter
        assert response.status_code == 400, (
            f"Expected status 400 for missing 'q' param, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Error schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )
        
        # Verify error message content
        response_json = response.json()
        assert "error" in response_json or "code" in response_json or "message" in response_json, (
            "Error response should contain error details"
        )

    def test_missing_required_param_dt(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that missing required parameter 'dt' returns 400 error.
        """
        test_case = endpoint_test_data[0]
        
        # Only provide 'q', missing 'dt'
        params = {
            "q": test_case.get("q")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API spec indicates 400 for invalid/missing parameters
        assert response.status_code == 400, (
            f"Expected status 400 for missing 'dt' param, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_missing_all_required_params(self, api_client, schema_validator):
        """
        Test that missing all required parameters returns appropriate error.
        Note: Without 'q' parameter, API returns 400 (Error code 1003).
        """
        params = {}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Missing required params should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for missing all required params, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_invalid_location_param_q(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that invalid location in 'q' parameter returns 400 error.
        Error code 1006: No location found matching parameter 'q'.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": "InvalidLocationXYZ12345NonExistent",
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid location should return 400 (Error code 1006)
        assert response.status_code == 400, (
            f"Expected status 400 for invalid location, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Error schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_invalid_date_format(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that invalid date format in 'dt' parameter returns 400 error.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": "invalid-date-format"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid date format should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for invalid date format, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_date_before_minimum_allowed(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that date before 1st Jan 2010 returns appropriate error.
        API spec states: Date on or after 1st Jan, 2010.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": "2009-12-31"  # Date before minimum allowed
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Date before minimum should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for date before minimum, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestHistoryAPIBoundaryConditions:
    """Test class for boundary conditions and edge cases."""

    def test_hour_boundary_minimum(self, api_client, endpoint_test_data, schema_validator):
        """
        Test hour parameter with minimum valid value (0 for midnight).
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "hour": 0  # Minimum valid hour
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Valid hour should return 200
        assert response.status_code == 200, (
            f"Expected status 200 for valid hour=0, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_hour_boundary_maximum(self, api_client, endpoint_test_data, schema_validator):
        """
        Test hour parameter with maximum valid value (23 for 11 PM).
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "hour": 23  # Maximum valid hour
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Valid hour should return 200
        assert response.status_code == 200, (
            f"Expected status 200 for valid hour=23, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_hour_invalid_above_maximum(self, api_client, endpoint_test_data, schema_validator):
        """
        Test hour parameter with value above maximum (24 or higher).
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "hour": 25  # Invalid hour above maximum
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid hour should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for invalid hour=25, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_hour_invalid_negative(self, api_client, endpoint_test_data, schema_validator):
        """
        Test hour parameter with negative value.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "hour": -1  # Invalid negative hour
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid hour should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for invalid hour=-1, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_end_dt_greater_than_dt(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that end_dt greater than dt works correctly.
        """
        # Find test case with end_dt
        test_case = None
        for tc in endpoint_test_data:
            if "end_dt" in tc:
                test_case = tc
                break
        
        if test_case is None:
            pytest.skip("No test case with end_dt found")
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "end_dt": test_case.get("end_dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        expected_status = test_case.get("statusCode", 200)
        assert response.status_code == expected_status, (
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_end_dt_before_dt(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that end_dt before dt returns error.
        API spec states: 'end_dt' should be greater than 'dt' parameter.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": "2024-02-20",
            "end_dt": "2024-02-15"  # end_dt before dt
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid date range should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for end_dt before dt, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_date_range_exceeds_30_days(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that date range exceeding 30 days returns error.
        API spec states: difference should not be more than 30 days.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": "2024-01-01",
            "end_dt": "2024-02-15"  # More than 30 days difference
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Date range exceeding 30 days should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for date range > 30 days, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestHistoryAPIResponseStructure:
    """Test class for validating response structure and content."""

    @pytest.mark.smoke
    def test_response_contains_location_object(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that successful response contains location object with expected fields.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        response_json = response.json()
        
        # Validate location object exists
        assert "location" in response_json, "Response should contain 'location' object"
        
        location = response_json["location"]
        
        # Validate expected location fields based on API spec
        expected_location_fields = ["name", "region", "country", "lat", "lon", "tz_id", "localtime"]
        for field in expected_location_fields:
            assert field in location, f"Location should contain '{field}' field"

    @pytest.mark.smoke
    def test_response_contains_forecast_object(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that successful response contains forecast object with expected structure.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        response_json = response.json()
        
        # Validate forecast object exists
        assert "forecast" in response_json, "Response should contain 'forecast' object"
        
        forecast = response_json["forecast"]
        
        # Validate forecastday array exists
        assert "forecastday" in forecast, "Forecast should contain 'forecastday' array"
        assert isinstance(forecast["forecastday"], list), "'forecastday' should be an array"
        assert len(forecast["forecastday"]) > 0, "'forecastday' array should not be empty"

    def test_forecastday_contains_expected_fields(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that forecastday objects contain expected fields.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        response_json = response.json()
        forecastday = response_json["forecast"]["forecastday"][0]
        
        # Validate expected forecastday fields based on API spec
        expected_fields = ["date", "day", "astro", "hour"]
        for field in expected_fields:
            assert field in forecastday, f"Forecastday should contain '{field}' field"

    def test_day_object_contains_weather_data(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that day object contains weather data fields.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        response_json = response.json()
        day = response_json["forecast"]["forecastday"][0]["day"]
        
        # Validate expected day fields based on API spec
        expected_day_fields = [
            "maxtemp_c", "maxtemp_f", "mintemp_c", "mintemp_f",
            "avgtemp_c", "avgtemp_f", "condition"
        ]
        for field in expected_day_fields:
            assert field in day, f"Day object should contain '{field}' field"

    def test_condition_object_structure(self, api_client, endpoint_test_data, schema_validator):
        """
        Test that condition object has expected structure.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        response_json = response.json()
        condition = response_json["forecast"]["forecastday"][0]["day"]["condition"]
        
        # Validate condition fields based on API spec
        expected_condition_fields = ["text", "icon", "code"]
        for field in expected_condition_fields:
            assert field in condition, f"Condition should contain '{field}' field"


class TestHistoryAPILocationTypes:
    """Test class for different location input types."""

    def test_location_by_city_name(self, api_client, endpoint_test_data, schema_validator):
        """
        Test History API with city name as location.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),  # City name from test data
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        expected_status = test_case.get("statusCode", 200)
        assert response.status_code == expected_status, (
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_location_by_coordinates(self, api_client, endpoint_test_data, schema_validator):
        """
        Test History API with latitude/longitude coordinates.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": "51.5074,-0.1278",  # London coordinates
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Coordinates should work and return 200
        assert response.status_code == 200, (
            f"Expected status 200 for coordinates, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_location_by_ip_address(self, api_client, endpoint_test_data, schema_validator):
        """
        Test History API with IP address as location.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": "auto:ip",  # Auto-detect by IP
            "dt": test_case.get("dt")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # IP-based location should work and return 200
        assert response.status_code == 200, (
            f"Expected status 200 for IP location, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestHistoryAPILanguageSupport:
    """Test class for language parameter support."""

    def test_language_parameter_english(self, api_client, endpoint_test_data, schema_validator):
        """
        Test History API with English language parameter.
        """
        # Find test case with lang parameter or use first one
        test_case = None
        for tc in endpoint_test_data:
            if "lang" in tc:
                test_case = tc
                break
        
        if test_case is None:
            test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "lang": "en"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200 for lang=en, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_language_parameter_invalid(self, api_client, endpoint_test_data, schema_validator):
        """
        Test History API with invalid language parameter.
        """
        test_case = endpoint_test_data[0]
        
        params = {
            "q": test_case.get("q"),
            "dt": test_case.get("dt"),
            "lang": "invalid_lang_code_xyz"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid language might still return 200 with default language
        # or return 400 depending on API implementation
        assert response.status_code in [200, 400], (
            f"Expected status 200 or 400 for invalid lang, got {response.status_code}. "
            f"Response: {response.text}"
        )
