# ********RoostGPT********

# Test generated by RoostGPT for test API-test-file using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /astronomy.json_get for http method type GET 
# RoostTestHash=656c29a7ca
# 
# 

# ********RoostGPT********
"""
Astronomy API Test Suite

This module contains comprehensive pytest tests for the Weather API Astronomy endpoint.
Tests cover success scenarios, error handling, and schema validation.

Setup:
    1. Install dependencies: pip install pytest requests pyyaml jsonschema
    2. Set environment variables:
       - API_HOST: API base URL (default: https://api.weatherapi.com)
       - key: Valid API key for authentication
    3. Ensure config.yml, api.json, and astronomy_json.json are in the test directory
    4. Run tests: pytest test_astronomy.py -v
    5. Run smoke tests only: pytest test_astronomy.py -v -m smoke
"""

import json
import os
import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator


# Constants
ENDPOINT = "/v1/astronomy.json"
API_SPEC_PATH = os.path.join(os.path.dirname(__file__), "api.json")
TEST_DATA_FILE = os.path.join(os.path.dirname(__file__), "astronomy_json.json")


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize the SwaggerSchemaValidator with the API spec."""
    return SwaggerSchemaValidator(API_SPEC_PATH)


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load test data from astronomy_json.json file."""
    with open(TEST_DATA_FILE, "r") as f:
        return json.load(f)


@pytest.fixture(scope="function")
def test_params(config_test_data, endpoint_test_data):
    """
    Merge config_test_data with endpoint_test_data.
    Endpoint test data overrides default config test data.
    """
    merged_data = []
    for test_case in endpoint_test_data:
        merged_case = {**config_test_data, **test_case}
        merged_data.append(merged_case)
    return merged_data


class TestAstronomyAPISuccess:
    """Test class for successful Astronomy API responses."""

    @pytest.mark.smoke
    def test_astronomy_success_scenarios(
        self, api_client, endpoint_test_data, schema_validator
    ):
        """
        Test successful astronomy API calls with valid parameters.
        
        This test iterates through all test cases in the JSON file
        and validates successful responses against the API schema.
        """
        for test_case in endpoint_test_data:
            if test_case.get("statusCode") != 200:
                continue
            
            params = {
                "q": test_case["q"],
                "dt": test_case["dt"]
            }
            
            response = api_client.get(ENDPOINT, params=params)
            
            # Assert status code
            assert response.status_code == test_case["statusCode"], (
                f"Scenario: {test_case.get('scenario', 'Unknown')} - "
                f"Expected status {test_case['statusCode']}, got {response.status_code}"
            )
            
            # Validate response schema
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, "GET", "200", response
            )
            assert validation_result["valid"], (
                f"Schema validation failed for scenario '{test_case.get('scenario')}': "
                f"{validation_result.get('message', 'Unknown error')}"
            )
            
            # Validate response structure
            response_json = response.json()
            assert "location" in response_json, "Response missing 'location' field"
            assert "astronomy" in response_json, "Response missing 'astronomy' field"
            
            # Validate location object
            location = response_json["location"]
            assert "name" in location, "Location missing 'name' field"
            assert "lat" in location, "Location missing 'lat' field"
            assert "lon" in location, "Location missing 'lon' field"
            
            # Validate astronomy object
            astronomy = response_json["astronomy"]
            assert "astro" in astronomy, "Astronomy missing 'astro' field"
            astro = astronomy["astro"]
            assert "sunrise" in astro, "Astro missing 'sunrise' field"
            assert "sunset" in astro, "Astro missing 'sunset' field"


class TestAstronomyAPIBadRequest:
    """Test class for 400 Bad Request scenarios."""

    def test_missing_required_param_q(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API response when required parameter 'q' is missing.
        
        Expected: 400 Bad Request with error code 1003
        """
        # Get a valid dt from test data
        valid_dt = endpoint_test_data[0]["dt"] if endpoint_test_data else "2024-01-15"
        
        params = {
            "dt": valid_dt
            # 'q' is intentionally missing
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API should return 400 for missing required parameter
        assert response.status_code == 400, (
            f"Expected 400 for missing 'q' parameter, got {response.status_code}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )
        
        # Validate error response structure
        response_json = response.json()
        assert "error" in response_json or "code" in response_json or "message" in response_json, (
            "Error response should contain error information"
        )

    def test_missing_required_param_dt(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API response when required parameter 'dt' is missing.
        
        Expected: 400 Bad Request
        """
        # Get a valid q from test data
        valid_q = endpoint_test_data[0]["q"] if endpoint_test_data else "London"
        
        params = {
            "q": valid_q
            # 'dt' is intentionally missing
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API should return 400 for missing required parameter
        assert response.status_code == 400, (
            f"Expected 400 for missing 'dt' parameter, got {response.status_code}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_invalid_location_query(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API response with invalid location query.
        
        Expected: 400 Bad Request with error code 1006 (No location found)
        """
        valid_dt = endpoint_test_data[0]["dt"] if endpoint_test_data else "2024-01-15"
        
        params = {
            "q": "InvalidLocationXYZ12345NonExistent",
            "dt": valid_dt
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API should return 400 for invalid location
        assert response.status_code == 400, (
            f"Expected 400 for invalid location, got {response.status_code}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_invalid_date_format(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API response with invalid date format.
        
        Expected: 400 Bad Request
        """
        valid_q = endpoint_test_data[0]["q"] if endpoint_test_data else "London"
        
        params = {
            "q": valid_q,
            "dt": "invalid-date-format"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API should return 400 for invalid date format
        assert response.status_code == 400, (
            f"Expected 400 for invalid date format, got {response.status_code}"
        )

    def test_empty_query_parameter(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API response with empty 'q' parameter.
        
        Expected: 400 Bad Request
        """
        valid_dt = endpoint_test_data[0]["dt"] if endpoint_test_data else "2024-01-15"
        
        params = {
            "q": "",
            "dt": valid_dt
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API should return 400 for empty required parameter
        assert response.status_code == 400, (
            f"Expected 400 for empty 'q' parameter, got {response.status_code}"
        )


class TestAstronomyAPIEdgeCases:
    """Test class for edge cases and boundary conditions."""

    def test_date_boundary_earliest_valid(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API with earliest valid date (1st Jan 2015).
        
        Per API spec, dates must be on or after 1st Jan, 2015.
        """
        valid_q = endpoint_test_data[0]["q"] if endpoint_test_data else "London"
        
        params = {
            "q": valid_q,
            "dt": "2015-01-01"  # Earliest valid date per spec
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Should succeed with valid earliest date
        assert response.status_code == 200, (
            f"Expected 200 for earliest valid date, got {response.status_code}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_date_before_minimum(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API with date before minimum allowed (before 1st Jan 2015).
        
        Expected: 400 Bad Request
        """
        valid_q = endpoint_test_data[0]["q"] if endpoint_test_data else "London"
        
        params = {
            "q": valid_q,
            "dt": "2014-12-31"  # Before earliest valid date
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API may return 400 for date before minimum
        # Note: Actual behavior depends on API implementation
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for date before minimum, got {response.status_code}"
        )

    def test_special_characters_in_query(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API with special characters in location query.
        
        Tests URL encoding and special character handling.
        """
        valid_dt = endpoint_test_data[0]["dt"] if endpoint_test_data else "2024-01-15"
        
        params = {
            "q": "São Paulo",  # Special character
            "dt": valid_dt
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Should handle special characters gracefully
        assert response.status_code in [200, 400], (
            f"Expected 200 or 400 for special characters, got {response.status_code}"
        )

    def test_coordinates_as_query(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API with latitude/longitude coordinates as query.
        
        Per API spec, coordinates in decimal degree format are valid.
        """
        valid_dt = endpoint_test_data[0]["dt"] if endpoint_test_data else "2024-01-15"
        
        params = {
            "q": "40.71,-74.01",  # New York coordinates
            "dt": valid_dt
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Should succeed with valid coordinates
        assert response.status_code == 200, (
            f"Expected 200 for coordinate query, got {response.status_code}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    def test_ip_address_as_query(self, api_client, endpoint_test_data, schema_validator):
        """
        Test API with IP address as query.
        
        Per API spec, IP addresses are valid query parameters.
        """
        valid_dt = endpoint_test_data[0]["dt"] if endpoint_test_data else "2024-01-15"
        
        params = {
            "q": "8.8.8.8",  # Google DNS IP
            "dt": valid_dt
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Should succeed with valid IP address
        assert response.status_code == 200, (
            f"Expected 200 for IP address query, got {response.status_code}"
        )


class TestAstronomyAPITableDriven:
    """Table-driven tests using data from JSON file."""

    def test_all_scenarios_from_json(
        self, api_client, endpoint_test_data, schema_validator
    ):
        """
        Execute all test scenarios defined in astronomy_json.json.
        
        This test iterates through each test case in the JSON file
        and validates the response against expected status code and schema.
        """
        for test_case in endpoint_test_data:
            scenario = test_case.get("scenario", "Unknown scenario")
            expected_status = test_case.get("statusCode")
            
            params = {
                "q": test_case["q"],
                "dt": test_case["dt"]
            }
            
            response = api_client.get(ENDPOINT, params=params)
            
            # Assert expected status code
            assert response.status_code == expected_status, (
                f"Scenario: {scenario} - "
                f"Expected status {expected_status}, got {response.status_code}"
            )
            
            # Validate response schema based on status code
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, "GET", str(expected_status), response
            )
            assert validation_result["valid"], (
                f"Scenario: {scenario} - Schema validation failed: "
                f"{validation_result.get('message', 'Unknown error')}"
            )
