# ********RoostGPT********

# Test generated by RoostGPT for test API-test-file using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /ip.json_get for http method type GET 
# RoostTestHash=5693e62dd1
# 
# 

# ********RoostGPT********
"""
IP Lookup API Test Suite

This module contains comprehensive pytest tests for the IP Lookup API endpoint.
The tests cover various scenarios including successful lookups, error handling,
and schema validation.

Setup:
    1. Ensure config.yml is properly configured with API host and authentication
    2. Set environment variables: API_HOST, key (for ApiKeyAuth)
    3. Place ip_json.json in the same directory as this test file
    4. Run tests: pytest test_ip_lookup.py -v
    5. Run smoke tests only: pytest test_ip_lookup.py -v -m smoke
"""

import json
import os
import pytest
from pathlib import Path
from validator import SwaggerSchemaValidator


# Load test data from JSON file
def load_endpoint_test_data():
    """Load test data from ip_json.json file."""
    test_data_path = Path(__file__).parent / "ip_json.json"
    with open(test_data_path, "r") as f:
        return json.load(f)


ENDPOINT_TEST_DATA = load_endpoint_test_data()

# API endpoint constant
IP_LOOKUP_ENDPOINT = "/v1/ip.json"

# Initialize schema validator
SPEC_PATH = Path(__file__).parent / "api.json"


@pytest.fixture(scope="module")
def schema_validator():
    """Initialize SwaggerSchemaValidator with API spec."""
    return SwaggerSchemaValidator(str(SPEC_PATH))


@pytest.fixture(scope="function")
def test_data_from_json():
    """Fixture to provide test data from JSON file."""
    return ENDPOINT_TEST_DATA


class TestIPLookupSuccess:
    """Test class for successful IP Lookup API scenarios."""

    @pytest.mark.smoke
    @pytest.mark.parametrize(
        "test_case",
        ENDPOINT_TEST_DATA,
        ids=[f"scenario_{i}_{tc['scenario']}" for i, tc in enumerate(ENDPOINT_TEST_DATA)]
    )
    def test_ip_lookup_success_scenarios(
        self, api_client, schema_validator, test_case
    ):
        """
        Test IP Lookup API with valid parameters from JSON test data.
        
        This test iterates through all test cases defined in ip_json.json
        and validates successful responses against the API schema.
        """
        # Prepare request parameters from test data
        params = {"q": test_case["q"]}
        expected_status = test_case["statusCode"]
        
        # Make API request
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        # Assert status code matches expected
        assert response.status_code == expected_status, (
            f"Expected status {expected_status}, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            IP_LOOKUP_ENDPOINT,
            "get",
            str(expected_status),
            response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message', 'Unknown error')}"
        )

    @pytest.mark.smoke
    def test_ip_lookup_with_valid_ip_address(self, api_client, schema_validator):
        """
        Test IP Lookup API with a valid IP address.
        
        Uses the first test case from JSON data to ensure required parameter is provided.
        """
        # Use first test case data for required parameter
        test_case = ENDPOINT_TEST_DATA[0]
        params = {"q": test_case["q"]}
        
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        # Validate response contains expected fields
        response_json = response.json()
        expected_fields = ["ip", "type", "continent_code", "continent_name", 
                          "country_code", "country_name", "city", "lat", "lon"]
        
        for field in expected_fields:
            assert field in response_json, f"Expected field '{field}' not found in response"
        
        # Validate schema
        validation_result = schema_validator.validate_schema_by_response(
            IP_LOOKUP_ENDPOINT, "get", "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )


class TestIPLookupErrorHandling:
    """Test class for IP Lookup API error scenarios."""

    def test_ip_lookup_missing_required_param_q(self, api_client, schema_validator):
        """
        Test IP Lookup API without required 'q' parameter.
        
        Expected: 400 Bad Request with error code 1003
        """
        # Make request without 'q' parameter
        response = api_client.get(IP_LOOKUP_ENDPOINT, params={})
        
        # API should return 400 for missing required parameter
        assert response.status_code == 400, (
            f"Expected status 400 for missing 'q' param, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            IP_LOOKUP_ENDPOINT, "get", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
        
        # Verify error response structure
        response_json = response.json()
        assert "error" in response_json or "code" in response_json, (
            "Error response should contain 'error' or 'code' field"
        )

    def test_ip_lookup_empty_q_parameter(self, api_client, schema_validator):
        """
        Test IP Lookup API with empty 'q' parameter.
        
        Expected: 400 Bad Request
        """
        params = {"q": ""}
        
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        # Empty parameter should result in 400
        assert response.status_code == 400, (
            f"Expected status 400 for empty 'q' param, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            IP_LOOKUP_ENDPOINT, "get", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )

    def test_ip_lookup_invalid_location(self, api_client, schema_validator):
        """
        Test IP Lookup API with invalid/non-existent location.
        
        Expected: 400 Bad Request with error code 1006
        """
        params = {"q": "invalidlocation12345xyz"}
        
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        # Invalid location should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for invalid location, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            IP_LOOKUP_ENDPOINT, "get", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )


class TestIPLookupBoundaryConditions:
    """Test class for boundary conditions and edge cases."""

    @pytest.mark.parametrize("special_input", [
        "   ",  # Whitespace only
        "!@#$%^&*()",  # Special characters
        "a" * 500,  # Very long string
    ])
    def test_ip_lookup_special_inputs(
        self, api_client, schema_validator, special_input
    ):
        """
        Test IP Lookup API with special/edge case inputs.
        
        These inputs should result in 400 Bad Request as they are not valid
        IP addresses or locations.
        """
        params = {"q": special_input}
        
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        # Special inputs should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for special input '{special_input[:20]}...', "
            f"got {response.status_code}. Response: {response.text}"
        )

    def test_ip_lookup_numeric_input(self, api_client, schema_validator):
        """
        Test IP Lookup API with numeric-only input that's not a valid IP.
        
        Expected: 400 Bad Request
        """
        params = {"q": "12345"}
        
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        # Numeric input that's not a valid IP should return 400
        assert response.status_code == 400, (
            f"Expected status 400 for numeric input, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestIPLookupResponseValidation:
    """Test class for detailed response validation."""

    @pytest.mark.smoke
    def test_ip_lookup_response_field_types(self, api_client, schema_validator):
        """
        Test that IP Lookup API response fields have correct types.
        
        Uses test data from JSON file for the request.
        """
        test_case = ENDPOINT_TEST_DATA[0]
        params = {"q": test_case["q"]}
        
        response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected status 200, got {response.status_code}. Response: {response.text}"
        )
        
        response_json = response.json()
        
        # Validate field types based on API spec
        if "ip" in response_json:
            assert isinstance(response_json["ip"], str), "Field 'ip' should be string"
        
        if "type" in response_json:
            assert isinstance(response_json["type"], str), "Field 'type' should be string"
        
        if "lat" in response_json and response_json["lat"] is not None:
            assert isinstance(response_json["lat"], (int, float)), "Field 'lat' should be number"
        
        if "lon" in response_json and response_json["lon"] is not None:
            assert isinstance(response_json["lon"], (int, float)), "Field 'lon' should be number"
        
        if "geoname_id" in response_json and response_json["geoname_id"] is not None:
            assert isinstance(response_json["geoname_id"], int), "Field 'geoname_id' should be integer"
        
        if "localtime_epoch" in response_json and response_json["localtime_epoch"] is not None:
            assert isinstance(response_json["localtime_epoch"], int), "Field 'localtime_epoch' should be integer"

    def test_ip_lookup_all_test_data_scenarios(
        self, api_client, schema_validator, test_data_from_json
    ):
        """
        Test IP Lookup API iterating through all test data scenarios.
        
        This test validates each scenario from the JSON test data file.
        """
        for idx, test_case in enumerate(test_data_from_json):
            params = {"q": test_case["q"]}
            expected_status = test_case["statusCode"]
            scenario = test_case["scenario"]
            
            response = api_client.get(IP_LOOKUP_ENDPOINT, params=params)
            
            assert response.status_code == expected_status, (
                f"Scenario {idx} '{scenario}': Expected status {expected_status}, "
                f"got {response.status_code}. Response: {response.text}"
            )
            
            # Validate response schema
            validation_result = schema_validator.validate_schema_by_response(
                IP_LOOKUP_ENDPOINT,
                "get",
                str(expected_status),
                response
            )
            assert validation_result["valid"], (
                f"Scenario {idx} '{scenario}': Schema validation failed: "
                f"{validation_result.get('message')}"
            )
