# ********RoostGPT********

# Test generated by RoostGPT for test API-test-file using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /current.json_get for http method type GET 
# RoostTestHash=4bfd44e81d
# 
# 

# ********RoostGPT********
"""
Pytest test suite for Weather API - Realtime Weather Endpoint

This module tests the /v1/current.json endpoint which provides current weather data.

Endpoint: /v1/current.json
Method: GET
Security: ApiKeyAuth (query parameter 'key')

Response Status Codes:
- 200: OK - Successful weather data retrieval
- 400: Bad Request - Invalid parameters (missing q, invalid URL, no location found)
- 401: Unauthorized - API key not provided or invalid
- 403: Forbidden - API key exceeded quota, disabled, or lacks access

To run tests:
    pytest test_current_weather.py -v
    pytest test_current_weather.py -v -m smoke  # Run only smoke tests
"""

import json
import os
import pytest
from pathlib import Path

# Import validator
from validator import SwaggerSchemaValidator


# Constants
ENDPOINT = "/v1/current.json"
API_SPEC_PATH = "api.json"
TEST_DATA_FILE = "current_json.json"


@pytest.fixture(scope="module")
def validator():
    """Initialize the SwaggerSchemaValidator with the API spec."""
    spec_path = Path(__file__).parent / API_SPEC_PATH
    return SwaggerSchemaValidator(str(spec_path))


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Load test data from current_json.json file."""
    test_data_path = Path(__file__).parent / TEST_DATA_FILE
    with open(test_data_path, 'r') as f:
        return json.load(f)


class TestRealtimeWeatherSuccess:
    """Test class for successful weather API responses."""

    @pytest.mark.smoke
    def test_get_current_weather_with_required_params(
        self, api_client, config_test_data, validator
    ):
        """
        Test successful weather retrieval with only required parameter 'q'.
        
        This is a smoke test that validates the happy path scenario
        using only required parameters.
        """
        # Load test data - use config_test_data if available, otherwise use default
        query_param = config_test_data.get('q', 'London')
        
        params = {"q": query_param}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Assert status code
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
        
        # Validate response structure
        response_json = response.json()
        assert "location" in response_json, "Response missing 'location' object"
        assert "current" in response_json, "Response missing 'current' object"
        
        # Validate location object has required fields
        location = response_json["location"]
        assert "name" in location, "Location missing 'name' field"
        assert "country" in location, "Location missing 'country' field"
        assert "lat" in location, "Location missing 'lat' field"
        assert "lon" in location, "Location missing 'lon' field"
        
        # Validate current object has required fields
        current = response_json["current"]
        assert "temp_c" in current, "Current missing 'temp_c' field"
        assert "temp_f" in current, "Current missing 'temp_f' field"
        assert "condition" in current, "Current missing 'condition' field"

    @pytest.mark.smoke
    def test_get_current_weather_table_driven(
        self, api_client, endpoint_test_data, validator
    ):
        """
        Table-driven test for successful weather retrieval scenarios.
        
        Iterates through all test cases defined in current_json.json
        and validates each scenario.
        """
        for test_case in endpoint_test_data:
            scenario = test_case.get("scenario", "Unknown scenario")
            expected_status = test_case.get("statusCode", 200)
            
            # Build params from test case - only include defined params
            params = {}
            if "q" in test_case:
                params["q"] = test_case["q"]
            if "lang" in test_case:
                params["lang"] = test_case["lang"]
            
            response = api_client.get(ENDPOINT, params=params)
            
            # Assert status code matches expected
            assert response.status_code == expected_status, (
                f"Scenario: {scenario} - Expected {expected_status}, "
                f"got {response.status_code}. Response: {response.text}"
            )
            
            # Validate response schema for successful responses
            if expected_status == 200:
                validation_result = validator.validate_schema_by_response(
                    ENDPOINT, "GET", "200", response
                )
                assert validation_result["valid"], (
                    f"Scenario: {scenario} - Schema validation failed: "
                    f"{validation_result.get('message')}"
                )
                
                response_json = response.json()
                assert "location" in response_json, (
                    f"Scenario: {scenario} - Response missing 'location'"
                )
                assert "current" in response_json, (
                    f"Scenario: {scenario} - Response missing 'current'"
                )


class TestRealtimeWeatherBadRequest:
    """Test class for 400 Bad Request scenarios."""

    def test_missing_required_param_q(self, api_client, validator):
        """
        Test that missing required parameter 'q' returns 400.
        
        Error code 1003: Parameter 'q' not provided.
        """
        # Make request without 'q' parameter
        response = api_client.get(ENDPOINT, params={})
        
        # API returns 400 for missing required parameter
        assert response.status_code == 400, (
            f"Expected 400 for missing 'q' param, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
        
        # Validate error response structure
        response_json = response.json()
        assert "error" in response_json or "code" in response_json, (
            "Error response should contain error details"
        )

    def test_invalid_location_param_q(self, api_client, validator):
        """
        Test that invalid location returns 400.
        
        Error code 1006: No location found matching parameter 'q'.
        """
        params = {"q": "invalidlocationxyz123456789"}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # API returns 400 for invalid location
        assert response.status_code == 400, (
            f"Expected 400 for invalid location, got {response.status_code}. "
            f"Response: {response.text}"
        )
        
        # Validate error response schema
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "400", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )

    def test_empty_q_parameter(self, api_client, validator):
        """
        Test that empty 'q' parameter returns 400.
        """
        params = {"q": ""}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Empty q should be treated as missing/invalid
        assert response.status_code == 400, (
            f"Expected 400 for empty 'q' param, got {response.status_code}. "
            f"Response: {response.text}"
        )

    @pytest.mark.parametrize("invalid_q", [
        "   ",  # Whitespace only
        "!@#$%^&*()",  # Special characters only
    ])
    def test_invalid_q_parameter_formats(self, api_client, invalid_q):
        """
        Test various invalid formats for 'q' parameter.
        """
        params = {"q": invalid_q}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid q formats should return 400
        assert response.status_code == 400, (
            f"Expected 400 for invalid 'q'='{invalid_q}', "
            f"got {response.status_code}. Response: {response.text}"
        )


class TestRealtimeWeatherUnauthorized:
    """Test class for 401 Unauthorized scenarios."""

    def test_missing_api_key(self, api_host):
        """
        Test that missing API key returns 401.
        
        Error code 1002: API key not provided.
        """
        import requests
        
        # Make request without API key
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        params = {"q": "London"}
        
        response = requests.get(url, params=params, timeout=30)
        
        # API returns 401 for missing API key
        assert response.status_code == 401, (
            f"Expected 401 for missing API key, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_invalid_api_key(self, api_host):
        """
        Test that invalid API key returns 401.
        
        Error code 2006: API key provided is invalid.
        """
        import requests
        
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        params = {
            "q": "London",
            "key": "invalid_api_key_12345"
        }
        
        response = requests.get(url, params=params, timeout=30)
        
        # API returns 401 for invalid API key
        assert response.status_code == 401, (
            f"Expected 401 for invalid API key, got {response.status_code}. "
            f"Response: {response.text}"
        )

    def test_empty_api_key(self, api_host):
        """
        Test that empty API key returns 401.
        """
        import requests
        
        url = f"{api_host.rstrip('/')}/{ENDPOINT.lstrip('/')}"
        params = {
            "q": "London",
            "key": ""
        }
        
        response = requests.get(url, params=params, timeout=30)
        
        # Empty API key should be treated as missing/invalid
        assert response.status_code == 401, (
            f"Expected 401 for empty API key, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestRealtimeWeatherOptionalParams:
    """Test class for optional parameter scenarios."""

    @pytest.mark.smoke
    def test_with_lang_parameter(self, api_client, config_test_data, validator):
        """
        Test weather retrieval with optional 'lang' parameter.
        """
        query_param = config_test_data.get('q', 'London')
        
        params = {
            "q": query_param,
            "lang": "en"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        # Validate response schema
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"], (
            f"Schema validation failed: {validation_result.get('message')}"
        )
        
        response_json = response.json()
        assert "current" in response_json
        assert "condition" in response_json["current"]
        assert "text" in response_json["current"]["condition"]

    @pytest.mark.parametrize("lang_code", ["es", "fr", "de", "zh"])
    def test_various_language_codes(self, api_client, config_test_data, lang_code):
        """
        Test weather retrieval with various language codes.
        """
        query_param = config_test_data.get('q', 'London')
        
        params = {
            "q": query_param,
            "lang": lang_code
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Should return 200 for valid language codes
        assert response.status_code == 200, (
            f"Expected 200 for lang={lang_code}, got {response.status_code}. "
            f"Response: {response.text}"
        )


class TestRealtimeWeatherQueryFormats:
    """Test class for various query parameter formats."""

    @pytest.mark.smoke
    def test_query_by_city_name(self, api_client, validator):
        """Test weather retrieval by city name."""
        params = {"q": "Paris"}
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"]

    def test_query_by_coordinates(self, api_client, validator):
        """Test weather retrieval by latitude/longitude coordinates."""
        # New York coordinates
        params = {"q": "40.71,-74.01"}
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"]

    def test_query_by_us_zipcode(self, api_client, validator):
        """Test weather retrieval by US zipcode."""
        params = {"q": "10001"}  # New York zipcode
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"]

    def test_query_by_ip_address(self, api_client, validator):
        """Test weather retrieval by IP address."""
        params = {"q": "auto:ip"}
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200, got {response.status_code}. Response: {response.text}"
        )
        
        validation_result = validator.validate_schema_by_response(
            ENDPOINT, "GET", "200", response
        )
        assert validation_result["valid"]


class TestRealtimeWeatherResponseValidation:
    """Test class for detailed response validation."""

    def test_location_object_fields(self, api_client, config_test_data, validator):
        """Validate all fields in the location object."""
        query_param = config_test_data.get('q', 'London')
        
        params = {"q": query_param}
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200
        
        response_json = response.json()
        location = response_json.get("location", {})
        
        # Validate location field types
        assert isinstance(location.get("name"), str)
        assert isinstance(location.get("region"), str)
        assert isinstance(location.get("country"), str)
        assert isinstance(location.get("lat"), (int, float))
        assert isinstance(location.get("lon"), (int, float))
        assert isinstance(location.get("tz_id"), str)
        assert isinstance(location.get("localtime_epoch"), int)
        assert isinstance(location.get("localtime"), str)

    def test_current_object_fields(self, api_client, config_test_data, validator):
        """Validate all fields in the current weather object."""
        query_param = config_test_data.get('q', 'London')
        
        params = {"q": query_param}
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200
        
        response_json = response.json()
        current = response_json.get("current", {})
        
        # Validate current field types
        assert isinstance(current.get("temp_c"), (int, float))
        assert isinstance(current.get("temp_f"), (int, float))
        assert isinstance(current.get("is_day"), int)
        assert isinstance(current.get("wind_mph"), (int, float))
        assert isinstance(current.get("wind_kph"), (int, float))
        assert isinstance(current.get("humidity"), (int, float))
        
        # Validate condition object
        condition = current.get("condition", {})
        assert isinstance(condition.get("text"), str)
        assert isinstance(condition.get("icon"), str)
        assert isinstance(condition.get("code"), int)

    def test_temperature_values_reasonable(self, api_client, config_test_data):
        """Validate temperature values are within reasonable bounds."""
        query_param = config_test_data.get('q', 'London')
        
        params = {"q": query_param}
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200
        
        response_json = response.json()
        current = response_json.get("current", {})
        
        temp_c = current.get("temp_c")
        temp_f = current.get("temp_f")
        
        # Temperature should be within Earth's recorded range
        assert -90 <= temp_c <= 60, f"Temperature {temp_c}°C out of reasonable range"
        assert -130 <= temp_f <= 140, f"Temperature {temp_f}°F out of reasonable range"
        
        # Verify Celsius to Fahrenheit conversion is approximately correct
        expected_f = (temp_c * 9/5) + 32
        assert abs(temp_f - expected_f) < 1, (
            f"Temperature conversion mismatch: {temp_c}°C should be ~{expected_f}°F, got {temp_f}°F"
        )
