# ********RoostGPT********

# Test generated by RoostGPT for test API-test-file using AI Type Claude AI and AI Model claude-opus-4-5-20251101
# 
# Test file generated for /forecast.json_get for http method type GET 
# RoostTestHash=462421f697
# 
# 

# ********RoostGPT********
"""
Pytest test suite for Weather API Forecast endpoint.

This module tests the /v1/forecast.json endpoint with comprehensive coverage
including happy path scenarios, edge cases, and error handling.

Setup:
    1. Install dependencies: pip install pytest requests pyyaml jsonschema
    2. Set environment variables:
        - API_HOST: API base URL (default: https://api.weatherapi.com)
        - key: Valid API key for authentication
    3. Run tests: pytest test_forecast.py -v
    4. Run smoke tests only: pytest test_forecast.py -v -m smoke
"""

import json
import os
import pytest
from pathlib import Path

# Import validator from validator.py
from validator import SwaggerSchemaValidator


# Initialize schema validator with API spec
SPEC_PATH = os.path.join(os.path.dirname(__file__), 'api.json')
schema_validator = SwaggerSchemaValidator(SPEC_PATH)

# Endpoint configuration
ENDPOINT = "/v1/forecast.json"
HTTP_METHOD = "GET"


def load_test_data_from_json():
    """Load test data from forecast_json.json file."""
    json_path = Path(__file__).parent / "forecast_json.json"
    with open(json_path, 'r') as f:
        return json.load(f)


@pytest.fixture(scope="module")
def endpoint_test_data():
    """Fixture to load endpoint-specific test data from JSON file."""
    return load_test_data_from_json()


@pytest.fixture(scope="function")
def build_request_params(config_test_data):
    """Factory fixture to build request parameters from test data."""
    def _build_params(test_case):
        # Start with config test data as base
        params = {}
        
        # Override with test case specific data
        # Required parameters
        if "q" in test_case:
            params["q"] = test_case["q"]
        elif "q" in config_test_data:
            params["q"] = config_test_data["q"]
            
        if "days" in test_case:
            params["days"] = test_case["days"]
        elif "days" in config_test_data:
            params["days"] = config_test_data["days"]
        
        # Optional parameters
        optional_params = ["dt", "unixdt", "hour", "lang", "alerts", "aqi", "tp"]
        for param in optional_params:
            if param in test_case:
                params[param] = test_case[param]
            elif param in config_test_data:
                params[param] = config_test_data[param]
        
        return params
    
    return _build_params


class TestForecastAPISuccess:
    """Test class for successful forecast API responses."""
    
    @pytest.mark.smoke
    def test_forecast_with_required_params_only(self, api_client, endpoint_test_data, build_request_params):
        """
        Test forecast API with only required parameters (q and days).
        This is the happy path scenario using only required fields.
        """
        # Find a test case with status code 200
        success_cases = [tc for tc in endpoint_test_data if tc.get("statusCode") == 200]
        assert success_cases, "No success test cases found in test data"
        
        # Use first success case but only required params
        test_case = success_cases[0]
        params = {
            "q": test_case.get("q"),
            "days": test_case.get("days")
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message')}"
        
        # Validate response structure
        response_json = response.json()
        assert "location" in response_json, "Response missing 'location' field"
        assert "current" in response_json, "Response missing 'current' field"
        assert "forecast" in response_json, "Response missing 'forecast' field"
    
    @pytest.mark.smoke
    def test_forecast_table_driven_success_scenarios(self, api_client, endpoint_test_data, build_request_params):
        """
        Table-driven test iterating through all success scenarios from JSON file.
        """
        success_cases = [tc for tc in endpoint_test_data if tc.get("statusCode") == 200]
        
        for test_case in success_cases:
            params = build_request_params(test_case)
            
            response = api_client.get(ENDPOINT, params=params)
            
            expected_status = test_case.get("statusCode")
            assert response.status_code == expected_status, (
                f"Scenario: {test_case.get('scenario')} - "
                f"Expected {expected_status}, got {response.status_code}: {response.text}"
            )
            
            # Validate response schema
            validation_result = schema_validator.validate_schema_by_response(
                ENDPOINT, HTTP_METHOD, str(expected_status), response
            )
            assert validation_result["valid"], (
                f"Scenario: {test_case.get('scenario')} - "
                f"Schema validation failed: {validation_result.get('message')}"
            )
    
    def test_forecast_with_all_optional_params(self, api_client, endpoint_test_data, build_request_params):
        """
        Test forecast API with all optional parameters included.
        Uses test case that has optional parameters defined.
        """
        # Find test case with optional params
        cases_with_optional = [
            tc for tc in endpoint_test_data 
            if tc.get("statusCode") == 200 and any(
                key in tc for key in ["dt", "lang", "alerts", "aqi"]
            )
        ]
        
        if not cases_with_optional:
            pytest.skip("No test cases with optional parameters found")
        
        test_case = cases_with_optional[0]
        params = build_request_params(test_case)
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message')}"
        
        response_json = response.json()
        
        # If aqi=yes was passed, verify air_quality is present
        if params.get("aqi") == "yes":
            current = response_json.get("current", {})
            assert "air_quality" in current, "Expected air_quality data when aqi=yes"
        
        # If alerts=yes was passed, verify alerts structure exists
        if params.get("alerts") == "yes":
            assert "alerts" in response_json, "Expected alerts data when alerts=yes"


class TestForecastAPIValidation:
    """Test class for request validation and error scenarios."""
    
    def test_missing_required_param_q(self, api_client, endpoint_test_data):
        """
        Test that missing 'q' parameter returns 400 error.
        Error code 1003: Parameter 'q' not provided.
        """
        # Get days from test data
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {"days": success_case.get("days", "3") if success_case else "3"}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Missing required param should return 400
        assert response.status_code == 400, f"Expected 400, got {response.status_code}: {response.text}"
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "400", response
        )
        assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message')}"
        
        response_json = response.json()
        error = response_json.get("error", response_json)
        assert error.get("code") == 1003, f"Expected error code 1003, got {error.get('code')}"
    
    def test_missing_required_param_days(self, api_client, endpoint_test_data):
        """
        Test that missing 'days' parameter returns appropriate error.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {"q": success_case.get("q", "London") if success_case else "London"}
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Missing days should return 400
        assert response.status_code == 400, f"Expected 400, got {response.status_code}: {response.text}"
    
    def test_invalid_location_param_q(self, api_client, endpoint_test_data):
        """
        Test that invalid location returns 400 error.
        Error code 1006: No location found matching parameter 'q'.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {
            "q": "InvalidLocationXYZ123456789",
            "days": success_case.get("days", "3") if success_case else "3"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 400, f"Expected 400, got {response.status_code}: {response.text}"
        
        # Validate error response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "400", response
        )
        assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message')}"
        
        response_json = response.json()
        error = response_json.get("error", response_json)
        assert error.get("code") == 1006, f"Expected error code 1006, got {error.get('code')}"


class TestForecastAPIBoundaryConditions:
    """Test class for boundary conditions and edge cases."""
    
    @pytest.mark.parametrize("days_value", [1, 14])
    def test_days_boundary_values(self, api_client, endpoint_test_data, days_value):
        """
        Test boundary values for 'days' parameter (1 and 14).
        Valid range is 1-14 according to API spec.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {
            "q": success_case.get("q", "London") if success_case else "London",
            "days": days_value
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, f"Expected 200 for days={days_value}, got {response.status_code}"
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message')}"
        
        # Verify forecast days count
        response_json = response.json()
        forecast_days = response_json.get("forecast", {}).get("forecastday", [])
        assert len(forecast_days) <= days_value, f"Expected at most {days_value} forecast days"
    
    @pytest.mark.parametrize("invalid_days", [0, 15, -1, "invalid"])
    def test_days_invalid_values(self, api_client, endpoint_test_data, invalid_days):
        """
        Test invalid values for 'days' parameter outside valid range.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {
            "q": success_case.get("q", "London") if success_case else "London",
            "days": invalid_days
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Invalid days should return 400
        assert response.status_code == 400, (
            f"Expected 400 for invalid days={invalid_days}, got {response.status_code}"
        )
    
    def test_empty_q_parameter(self, api_client, endpoint_test_data):
        """
        Test empty string for 'q' parameter.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {
            "q": "",
            "days": success_case.get("days", "3") if success_case else "3"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        # Empty q should return 400
        assert response.status_code == 400, f"Expected 400, got {response.status_code}"


class TestForecastAPILocationFormats:
    """Test class for different location format inputs."""
    
    @pytest.mark.parametrize("location_type,location_value", [
        ("city_name", "Paris"),
        ("coordinates", "48.8566,2.3522"),
        ("us_zipcode", "10001"),
    ])
    def test_various_location_formats(self, api_client, endpoint_test_data, location_type, location_value):
        """
        Test different location format inputs for 'q' parameter.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        
        params = {
            "q": location_value,
            "days": success_case.get("days", "3") if success_case else "3"
        }
        
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200, (
            f"Expected 200 for {location_type}={location_value}, got {response.status_code}"
        )
        
        # Validate response schema
        validation_result = schema_validator.validate_schema_by_response(
            ENDPOINT, HTTP_METHOD, "200", response
        )
        assert validation_result["valid"], f"Schema validation failed: {validation_result.get('message')}"


class TestForecastAPIResponseStructure:
    """Test class for validating response structure and content."""
    
    def test_response_contains_location_details(self, api_client, endpoint_test_data, build_request_params):
        """
        Test that response contains complete location details.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        assert success_case, "No success test case found"
        
        params = build_request_params(success_case)
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200
        
        response_json = response.json()
        location = response_json.get("location", {})
        
        # Verify location fields exist
        expected_location_fields = ["name", "region", "country", "lat", "lon", "tz_id", "localtime"]
        for field in expected_location_fields:
            assert field in location, f"Location missing field: {field}"
    
    def test_response_contains_current_weather(self, api_client, endpoint_test_data, build_request_params):
        """
        Test that response contains current weather data.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        assert success_case, "No success test case found"
        
        params = build_request_params(success_case)
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200
        
        response_json = response.json()
        current = response_json.get("current", {})
        
        # Verify current weather fields exist
        expected_current_fields = ["temp_c", "temp_f", "condition", "wind_mph", "humidity"]
        for field in expected_current_fields:
            assert field in current, f"Current weather missing field: {field}"
    
    def test_response_contains_forecast_data(self, api_client, endpoint_test_data, build_request_params):
        """
        Test that response contains forecast data with correct structure.
        """
        success_case = next(
            (tc for tc in endpoint_test_data if tc.get("statusCode") == 200), 
            None
        )
        assert success_case, "No success test case found"
        
        params = build_request_params(success_case)
        response = api_client.get(ENDPOINT, params=params)
        
        assert response.status_code == 200
        
        response_json = response.json()
        forecast = response_json.get("forecast", {})
        
        assert "forecastday" in forecast, "Forecast missing 'forecastday' field"
        
        forecastday = forecast.get("forecastday", [])
        assert len(forecastday) > 0, "Forecast should contain at least one day"
        
        # Verify first forecast day structure
        first_day = forecastday[0]
        assert "date" in first_day, "Forecast day missing 'date' field"
        assert "day" in first_day, "Forecast day missing 'day' field"
        assert "astro" in first_day, "Forecast day missing 'astro' field"
        assert "hour" in first_day, "Forecast day missing 'hour' field"
